### ISSUE TITLE
Revamp Code of Conduct

### ISSUE THREAD

**Issue by ha0ye** [UF-Carpentry/Coordination#100]
Relying on the Carpentries CoC is fine, but I think we can improve by having more explicit description of both expected behavior and not-tolerated behavior.

Also, explicit reporting guidelines would be useful.

The Davis R-Users Group has a nice example.
https://d-rug.github.io/code-of-conduct.html

**Comment by ha0ye** [comment]
Dropping in a few more examples:
* https://www.opencon2018.org/code_of_conduct
* https://www.mozilla.org/en-US/about/governance/policies/participation/

**Comment by ha0ye** [comment]
Some more examples:
* https://bio-diversity.org/blog/2019/6/27/the-2019-evolution-meeting-exemplified-how-to-make-scientific-conferences-inclusive-spaces
* https://facultysexualmisconduct.com/code-of-conduct/

**Comment by gaurav** [comment]
Possibly useful: https://twitter.com/BeckSamBar/status/1148331250555527168?s=20

**Comment by ha0ye** [comment]
remaining tasks
* Alethea and Flora as contacts for reporting? (and check with them)
* set-up anonymous google form for reporting
* google groups email #120
