### ISSUE TITLE
Agenda Items for Board Meeting on 2019, May 14

### ISSUE THREAD

**Issue by ha0ye** [UF-Carpentry/Coordination#101]
Here's a preliminary list - please add any agenda items that you'd like to discuss for our next meeting.
1. Approve last week's minutes -- uf-carpentry/website#39
2. Logo design updates
3. Travel award updates
4. TREC workshop debrief
5. Biodiversity 1-day geospatial debrief
6. ResBaz planning updates
7. USDA machine learning workshop #99 
8. Planning for Carpentries membership renewal
    - request amount + incentives
    - draft message
    - who to ask
    - update on IFAS funding
9. Draft plan for need-based scholarship / fee reduction
10. Draft social media / website guidelines
11. Discuss long-term plan for REC program

**Comment by ha0ye** [comment]
I will be out of town, so it's not ideal for me to remote in to chair... @picardis, you were nominated to fill in - can we switch chairing duties for next time and then a future time? I'm happy to continue coordinating the agenda up until the actual meeting itself.

**Comment by picardis** [comment]
I can definitely do that! No problem. Also I have an agenda item to add:

11. Discuss long-term plan for REC program.

But I'd like to see if Zack Brym can join. I had a conversation with him about this after the TREC workshop and I think he should participate in our discussion. If he can't this time, maybe we can leave this item for some other time. I'll let you all know.

**Comment by gklarenberg** [comment]
Addition to 8: Update on IFAS funding

**Comment by picardis** [comment]
I just heard back from Zack - he will be at the meeting today. So item 11 is confirmed as part of the agenda, I will bump it up a bit so that Zack doesn't have to sit through the entire meeting if he doesn't want to.

**Comment by elisemorrison** [comment]
Here's the HackMD page for this week's meeting: 
https://hackmd.io/D6gAK5P1TNenGrviSuhT7w
