### ISSUE TITLE
Research Bazaar Initial Planning

### ISSUE THREAD

**Issue by ha0ye** [UF-Carpentry/Coordination#102]
- [x] draft an opening message for potential collaborators
    * describe ResBaz vision
    * preliminary info on events/timing
    * coordinate an in-face meeting to address questions, identify interests
- [x] contact potential collaborators and setup initial meeting
- [x] setup shared planning files (google docs?)
- [ ] website dev

**Comment by ha0ye** [comment]
Initial hackmd notes - https://hackmd.io/LSW0ANWeRgKu-PNuEFWQ_w

**Comment by ha0ye** [comment]
@josephaandreoli and @elisemorrison,

I drafted an email to send out to folks - it's in the google drive folder. Can you two look it over and add any edits/comments you want?

I think the poll for the first meeting can span the two weeks of May 20-24 and May 27-31, with the goal of sending out emails to contacts early next week (Monday/Tuesday), assuming we reach a consensus on the text.

**Comment by josephaandreoli** [comment]
Hey Hao, I've requested access to the Google Drive linked to above.

**Comment by ha0ye** [comment]
> Hey Hao, I've requested access to the Google Drive linked to above.

My bad - I think I fixed the permissions now, can you try again?

**Comment by josephaandreoli** [comment]
I'm in

**Comment by elisemorrison** [comment]
I think the email looks good - I have some minor edits to some of the text. I requested edit access on the google doc.

**Comment by ha0ye** [comment]
> I think the email looks good - I have some minor edits to some of the text. I requested edit access on the google doc.

I wasn't able to find the request, but you should have edit access now.

**Comment by elisemorrison** [comment]
Thanks - made some minor edits - looks good to me!

**Comment by josephaandreoli** [comment]
Made edits too according to @ha0ye's comments. I think we're good!

**Comment by gklarenberg** [comment]
@ha0ye See Alethea's email: "Please get the ResBaz dates to Flora or myself as soon as you can, even if they are a guess at this point. Going into June/July our calendar for the space will fill up quickly. So even if you have a range of dates—I recommend putting them on hold with us. Otherwise you might not have the space."

**Comment by ha0ye** [comment]
> @ha0ye See Alethea's email: "Please get the ResBaz dates to Flora or myself as soon as you can, even if they are a guess at this point. Going into June/July our calendar for the space will fill up quickly. So even if you have a range of dates—I recommend putting them on hold with us. Otherwise you might not have the space."

Thanks, I’m hoping to get a meeting going sometime in the next two weeks, and setting the date will be first on the agenda.

@josephaandreoli and @elisemorrison Sounds like we’re good to go on initial email contact, so I’ll take care of that tonight.

**Comment by ha0ye** [comment]
Based on survey responses, it looks like Thursdays at 9am accommodates most folks. I'm reaching out to Flora and Alethea to reserve the UFII conference room for that time slot on a weekly basis, so that it's available for us for planning meetings.

@josephaandreoli and @elisemorrison Does that timing work for you? If not, can you fill out the scheduling survey http://whenisgood.net/t98s4gq

**Comment by josephaandreoli** [comment]
Hey all, I have an appointment this Thursday at 9:30. They're usually on Mondays so it shouldn't be a problem after this first meeting.

**Comment by gklarenberg** [comment]
I'll be there - as an R-ladies organizer :)

**Comment by ha0ye** [comment]
> I'll be there - as an R-ladies organizer :)

Yay, you and Javi both responded - sorry if my bcc'ing of the 2nd email prevented coordination between you two.

**Comment by ha0ye** [comment]
Moving planning over to google docs, and closing this issue.
