### ISSUE TITLE
Develop guidelines for social media and web

### ISSUE THREAD

**Issue by ha0ye** [UF-Carpentry/Coordination#105]
We have a website, twitter, and facebook, but no guidelines on usage yet (for content or how to promote events, etc.)

R-Ladies has one that we could use / adapt - https://github.com/rladies/starter-kit/blob/master/Social_Media_Guide_for_Chapters.pdf

**Comment by gaurav** [comment]
Pull request up at https://github.com/UF-Carpentry/website/pull/41!
