### ISSUE TITLE
Collect / organize curriculum-specific tips

### ISSUE THREAD

**Issue by ha0ye** [UF-Carpentry/Coordination#106]
We often have experience or post-workshop feedback on what worked well and what didn't. A public record of this info would help for organizing and running future workshops.

It's unclear what the ideal space for this would be - @justinmillar started a repo specifically for the geospatial workshop https://github.com/UF-Carpentry/geospatial-pilot-notes

**Comment by picardis** [comment]
Duplicate of #96
