### ISSUE TITLE
Add instructor info for 2019-04-29-uf-trec and 2019-05-07-ufbi-ifas-geospatial

### ISSUE THREAD

**Issue by ha0ye** [UF-Carpentry/Coordination#108]
to the "instructors" file in the shared google drive folder "SwC_DC_UF"

(Note that I'm deprecating "MergedInstructors" in favor of a long-form data structure)

**Comment by picardis** [comment]
Done

**Comment by stuckyb** [comment]
Thanks for the reminder, @ha0ye.  I added the personnel from the May 7 workshop.
