### ISSUE TITLE
Agenda items for Board Meeting on May 28, 2019

### ISSUE THREAD

**Issue by picardis** [UF-Carpentry/Coordination#109]
- [ ] Approve last week's minutes 

- [ ] Update on logo approval from UF 

- [ ] Update on IFAS funding

- [ ] Define target sponsors for membership renewal

- [ ] Define incentives for sponsors

- [ ] Update on ResBaz planning 

- [ ] Make decision on need-based scholarship/fee reduction

- [ ] Social media/website guidelines

- [ ] Documenting curriculum-specific tips

- [ ] Revamp Code of Conduct

- [ ] Preliminary workshop schedule for Fall 2019

- [ ] Summer workshops

- [ ] Update on USDA/UF machine learning workshop

**Comment by picardis** [comment]
Please add/modify as needed.

**Comment by elisemorrison** [comment]
Here's the link to the HackMD page
https://hackmd.io/2AM0vzNzSwyXBUAIGDAQMw
