### ISSUE TITLE
Bug BBQ

### ISSUE THREAD

**Issue by fmichonneau** [UF-Carpentry/Coordination#11]
The Carpentries are organizing a bug BBQ on April 12 and 13. More details here: http://www.datacarpentry.org/2018-03-07-bug-bbq

In the blog post we mention the Geospatial and Social Science Curriculum because that's the main push, but I think other lessons are going to join in so many different disciplines are going to be represented.

I think it would be great to have a group together from the UF Carpentry Club in the same physical space (if only for a couple of hours) to work on some of the issues that will be raised during the Bug BBQ. Would that be of interest to the Club? If so, I'd be happy to help organizing it.

**Comment by ha0ye** [comment]
I agree that we should have an organized event. I would also like to reach out some of the social science departments to participate (and hook them on the whole Carpentries thing).

**Comment by fmichonneau** [comment]
that would be great!

**Comment by gklarenberg** [comment]
I'm game

**Comment by justinmillar** [comment]
@ha0ye Raffaele Vacca would be a good person to reach out to.
https://soccrim.clas.ufl.edu/directory/sociology/raffaele-vacca-2/
http://www.raffaelevacca.com/

**Comment by fmichonneau** [comment]
have you had a chance to contact Raffaele? Should we set up a time to meet to discuss the organization of the event?

**Comment by ha0ye** [comment]
@fmichonneau The board is meeting at 2pm today in the UFII conference room. This event is on the agenda. Will you be around, or would you like a video-conf link?

**Comment by fmichonneau** [comment]
Great! Unfortunately I'll be in another meeting at this time. Let me know what you decide or how I can help.

**Comment by ha0ye** [comment]
@justinmillar I'm leaving town next Thursday, so let's get rolling on this quick (at least the scheduling part).

How do you feel about Friday afternoon? (Friday the 13th !! :ghost:) We can go over how to contribute say 1-1:30pm, and then have a room booked. Timing-wise, I feel like people are more willing to escape normal work by then, and we can see if there's informal interest in happy hour celebrations afterward.

**Comment by justinmillar** [comment]
@ha0ye That works fine for me, I can email Flora to see if we can book the UFII seminar room for that whole afternoon.

**Comment by ha0ye** [comment]
Task list

- [ ] arrange space
- [ ] arrange snacks and refreshments (@mjcollin, is it reasonable for the Board to spend some money to provide coffee and afternoon snacks?)
- [ ] contact folks who can boost the message to their departments
- [ ] make announcement message for distribution
- [ ] create instructions for participants
- [ ] prepare walkthrough of GitHub for new participants

**Comment by ha0ye** [comment]
@justinmillar I set up a wiki page here. Please look it over:
https://github.com/UF-Carpentry/Coordination/wiki/2018-April-Bug-BBQ-Info

I figure we can use it to draft up the announcement message for email distribution, and then keep it up for reference or if we need to update it.

**Comment by justinmillar** [comment]
@ha0ye This looks great, nice job!

I'm not sure exactly how this works, but won't contributors be recognized when the lessons are submitted to Zenodo? This could be worth mentioning under the "What do I get out of it?" question as a potential CV builder. Maybe @fmichonneau could clarify?

**Comment by fmichonneau** [comment]
Yes, we list all contributors in our lesson releases on Zenodo, so contributing to Carpentries lessons can be listed on a CV (with a citable DOI).

**Comment by ha0ye** [comment]
@fmichonneau Thanks! I thought that was the case, but I didn't see any DOI / Zenodo links on the repos. I added this info to the wiki page.

**Comment by fmichonneau** [comment]
Not all of our lessons have been published/have a DOI. There also have been some inconsistencies in how or whether this information is listed. It's something we'll be working on soon!

**Comment by ha0ye** [comment]
@fmichonneau I know one of the challenges in this space is that after you mint a DOI for a repo, adding that DOI badge to the repo is a change, and won't be reflected when you try to resolve that DOI link. 

I think this may be mostly resolved by Zenodo adding in the concept DOIs which always point to the most recent version of a record. I've done this to just have a static DOI badge in the repo README, which always resolves to the most recent release version.

**Comment by ha0ye** [comment]
Event is done! Thanks everyone. There may be follow-up surveys for the participants, but I'm going to go ahead and close this issue.
