### ISSUE TITLE
Agenda Items for Board Meeting on June 25, 2019

### ISSUE THREAD

**Issue by ha0ye** [UF-Carpentry/Coordination#112]
- [ ] approve last week's minutes
- [ ] logo next steps
    * stickers?
    * website makeover?
- [ ] general funding updates
    * IFAS - $10,000
    * UFII/UFBI - $3,750
    * UF Libraries - $1,500
    * WEC - $1,500
- [ ] other requests for renewal/operation funding
    * EPI (Geraldine?)
    * Museum (Brian & Gaurav)
- [ ] ResBaz planning updates
    * preliminary schedule ready, details to be ironed out for exact timing, contacts, etc.
- [ ] REC Program
    * add information and description of commitment to website - https://www.uf-carpentries.org/about/workshops or https://www.uf-carpentries.org/about/ ?
    * this may need to include information about travel to Gainesville for instructor training (make it a regularly-scheduled special travel award?)
- [ ] identify election board for Fall
- [ ] identify travel award selection committee for Fall
- [ ] standardize communications (e.g. intro slides, requests for volunteer instructors/helpers)
    * be clear that workshop helping/teaching does not require prior instructor training (though prefer experience if signing up to be an instructor) - increase accessibility to volunteer with us
- [ ] UF/USDA machine learning workshop updates
- [ ] revamping Code of Conduct
- [ ] preliminary workshop schedule for Fall 2019
- [ ] summer workshops
- [ ] select chair and secretary for next 2 meetings

Please add/modify as needed. (non-board members may only be able to add comments)

**Comment by gaurav** [comment]
I'll try to join in on the meeting on Zoom, but might not be able to as I'm still at the Evolution conference.

I should be able to serve as either chair or secretary for July 9 and 23, so feel free to make me one of those if nobody else wants to. I'll have more time for that in August as well.
