### ISSUE TITLE
Agenda Items for Board Meeting on July 9, 2019

### ISSUE THREAD

**Issue by ha0ye** [UF-Carpentry/Coordination#113]
(forgot to add this to last meeting)
* funding for 1 day of lunch for Research Bazaar (with other sources covering the other days)

* pre-planning for Data Carpentry Genomics workshop

**Comment by gaurav** [comment]
First stab at other agenda items (feel free to edit this comment and add more!):
- Approve [last week's minutes](https://www.uf-carpentries.org/minutes/board-2019-06-25/)
- Funding review for membership review (#103)
  - IFAS ($10,000) + UFII ($3,750) + UF Libraries ($1,500) + WEC ($1,500) + FLMNH ($1,500) = $18,250
  - UFII funding earmark for travel (#116)
- Identify election board for Fall
- Identify travel award selection committee for Fall
- Scheduling workshops and events
  - ResBaz update
    - Funding for 1 day of lunch for Research Bazaar (with other sources covering the other days)
  - Machine Learning / Tensorflow workshop update
  - Fall workshop in genomics (#114)
    - Pre-planning for Data Carpentry Genomics workshop
  - Spring workshop in machine learning or network analysis (#115)
- Improvements to our website
  - Add pathways / "Get Involved" page to the website (#82)
- Updates on Code of Conduct revamp (#100)

**Comment by ha0ye** [comment]
Hackmd notes: https://hackmd.io/@EToFOnPVTuGXM_GVI0LK4A/B1gBtDMWr
