### ISSUE TITLE
Agenda items for Board Meeting on Jul 23, 2019

### ISSUE THREAD

**Issue by gaurav** [UF-Carpentry/Coordination#118]
- Approve [last week's minutes](https://www.uf-carpentries.org/minutes/board-2019-07-09/)
- Carpentry membership logistics (#119)
  - Any further updates on fundraising? Are we done for this year? (#103)
  - Review membership agreement with The Carpentries
  - Who will be our designated signee/local contact for the agreement?
  - Who should represent us on the The Carpentries Member Organisation Council?
- Setting up a group-account for the entire board on Google Groups (#120)
- Approve new Code of Conduct (#100)
  - Pull request now up at UF-Carpentry/website#45
- Updates on [USDA-ARS/UF Machine Learning Training 2019](https://usda-ars-gbru.github.io/ml-training-site/) (Aug 27-28)
- Start publicizing workshops for fall 2019/spring 2020 (#121)
- Should we make our Carpentries report public? (#69)
- Update on stickers

**Comment by ha0ye** [comment]
hackmd link:
https://hackmd.io/-IRsYHHASw6AoeogauPHtg
