### ISSUE TITLE
Use a google group for email?

### ISSUE THREAD

**Issue by ha0ye** [UF-Carpentry/Coordination#120]
We currently have a ufcarpentries@gmail.com email inbox, but it can't auto-forward to multiple folks. However, we might be able to set up a google groups account that will work to facilitate a common inbox for the board to use:
https://support.google.com/a/answer/167430

**Comment by gaurav** [comment]
I just created this group and sent out invites to all current board members. If you don't get an invite, let me know and I'll send it out again!
