### ISSUE TITLE
Start publicizing workshops for Fall 2019

### ISSUE THREAD

**Issue by gaurav** [UF-Carpentry/Coordination#121]
At last week's board meeting, we [started planning](https://www.uf-carpentries.org/minutes/board-2019-07-09/) our slate of workshops for Fall 2019 (#75, #98) and Spring 2020 (#114, #115). I think we should put this up on our website somewhere, either as a blog post describing our intentions or as events that include "(proposed)", "(tentative)" or "(in planning)" in their title. That would be something for people to look forward to and might encourage feedback on how those dates work for prospective students, trainers and helpers. August isn't very too away!

**Comment by ha0ye** [comment]
We also have the following dates reserved for the UFII classroom in Spring 2020:
2/10-2/11

3/9-3/10

3/30-3/31

4/6-4/7

4/20-4/21

**Comment by ha0ye** [comment]
I have events created on the website, that can be modified as details get decided on.

**Comment by stuckyb** [comment]
An [upcoming events blog post](https://www.uf-carpentries.org/posts/2019-08-05-upcoming-events/) is now also live, thanks to @gklarenberg .
