### ISSUE TITLE
Create registration form for USDA-ARS/UF Machine Learning Training 2019

### ISSUE THREAD

**Issue by gaurav** [UF-Carpentry/Coordination#122]
The instructors of the Machine Learning workshop on Aug 27-28 met today (https://github.com/USDA-ARS-GBRU/ml-training-site/issues/2). We're aiming for 55-60 students, of which 32 slots have been claimed by USDA/ARS. We can therefore register 25 people to join this course. Note that there is a prerequisite for this training: students must be competent with Python before taking this course.

I can coordinate with Alethea to get the registration page set up, but wanted to check with you all about:
 - Should we charge our usual training fee for this workshop? I think yes, but it is a first-time course.
 - The current plan is for students to get coffee/lunch in the Reitz Union or nearby at their own expense. Should we consider paying for coffee at coffee breaks so that students can socialize a bit in the breaks? Not necessary but I think it would be nice.
 - Should we try to give our sponsoring organizations priority access to half the seats at this registration as proposed in https://github.com/UF-Carpentry/Coordination/issues/86#issuecomment-488103597?

Let me know if there's anything else I haven't thought of!

**Comment by gklarenberg** [comment]
My suggestion would be to charge less - to cover the coffee breaks.
And yes, I feel offering the seats to the sponsoring orgs/deps would be appropriate. Timeline's getting a little tight though, so we should get with Alethea or Flora asap.

**Comment by ha0ye** [comment]
I don't know how complicated it would be to cater coffee at the Reitz Union. If it's not something we can do simply, I think we should forego fees altogether and do registration, but without a charge (but do let know folks know that they'll be on their own for coffee / lunch)

**Comment by gaurav** [comment]
Alethea tells me that catering coffee at Reitz isn't too complicated if we have the right space, but Classic Fare would charge us $150 per coffee break ($200 if we also want to provide decaf) for 60 people. Assuming a morning and afternoon break (students are on their own for lunch), that would be $300-$400 per day or $600-$800 for both days of the workshop.

If we want our 25 students to pay for coffee for everybody, that would come to $24-$32/person for the entire workshop, plus credit card processing bills. I think that's too high, and so I think we should go with Hao's proposal to forego fees entirely. If we do that, we don't need to go through the UF registration system, and can just create an event on Eventbrite or with a Google Form.

I'll add this to the agenda for tomorrow's board meeting.

**Comment by stuckyb** [comment]
As far as I know, this is all settled and the registration forms are active, so I think this can be closed.
