### ISSUE TITLE
Coordinate Board Elections for Fall 2019

### ISSUE THREAD

**Issue by ha0ye** [UF-Carpentry/Coordination#126]
- [x] Decide on timing of announcement/solicitation, voting, decision
    * announcement of elections (week of August 26)
    * self-nomination deadline (September 4)
    * ballots out (week of September 9, due back September 17)
    * ballot results and deciding new board members (September 18 through September 27)
- [x] Wording of announcement/solicitation
- [x] Distribution channels for announcement/solicitation
    * Informatics-teaching listserv
    * Website
    * Twitter
- [x] Generate nomination form
- [x] Review candidate eligibility
- [x] Create ballots and update website
- [x] Distribute ballots
- [x] Send voting reminder (morning of Monday, Sept 23)
- [x] Collect votes (morning of Tuesday, Sept 24)
- [ ] (whole board) approves new board (Wednesday, Sept 25)

**Comment by ha0ye** [comment]
Previous announcement text:

> Interested in advancing informatics skills and reproducible science at UF? Join the Carpentry Club board!
> 
> The board is composed of 7 representatives, who guide the workshop schedule, interface with the supporters, and create opportunities for peer learning at UF and beyond. As a member of the Board, you will be exposed to networking with data science peers from a variety of backgrounds, be involved in the organizational aspects of the largest cross-departmental group doing informatics literacy at UF, and help make the local Carpentries community grow and be successful.
> The [Carpentries](https://carpentries.org/) is an international organization that teaches foundational coding and data science skills to researchers worldwide. The UF Carpentries Club is dedicated to bringing their inclusive and supportive culture and curricula to the University of Florida, primarily by teaching 2-day workshops in R and Python.
> 
> If you would like to become more involved in lesson planning, teaching, or more, please consider self-nominating for a board position!
> Our board is composed of 7 representatives, who guide the workshop schedule, interface with our supporters, and create opportunities for peer learning at UF and beyond. As a member of the Board, you will be exposed to networking with data science peers from a variety of backgrounds, be involved in the organizational aspects of the largest cross-departmental group doing informatics literacy at UF, and help make the local Carpentries community grow and be successful.
> 
> If you would like to become more involved in lesson planning, teaching, community building, and more, please consider self-nominating for a board position.

**Comment by ha0ye** [comment]
I'll go ahead and start a PR to the website with proposed announcement text, etc.

**Comment by picardis** [comment]
Nomination form is here: https://docs.google.com/forms/d/17MYDBDKqLENdpTkK5knsWwGciYkzQowPqNDuEh1Wgn8/edit
