### ISSUE TITLE
Agenda for September 10 Board meeting

### ISSUE THREAD

**Issue by picardis** [UF-Carpentry/Coordination#129]
- Approve last week's minutes
- Status on elections (new schedule, current nominations, social event, AOB)
- Status on travel awards
- Status on ResBaz
- Status on upcoming workshops:
  - Genomics (Fall)
  - Ecology (October)
  - Social sciences (TBD)
  - UCF (TBD)
  - ML/network analysis (Spring)

**Comment by elisemorrison** [comment]
https://hackmd.io/HE8VXn3MT066WrYxE5NT4Q
