### ISSUE TITLE
Agenda for September 25 meeting

### ISSUE THREAD

**Issue by picardis** [UF-Carpentry/Coordination#130]
- Approve last week’s minutes
- Approve new board
- Elections debrief
- Handover documents
- UF Ally Skills Network request for money for snacks (Oct 14 workshop)
- ResBaz debrief
- Status on upcoming workshops: Ecology (October), Genomics (Fall)

**Comment by gaurav** [comment]
* Start planning the [Social Sciences workshop](https://datacarpentry.org/socialsci-workshop/) for Spring 2020 (I've invited [Prof. Kroff](https://people.clas.ufl.edu/jvaldeskroff/) and a few others to join us based on suggestions from Sasha).

**Comment by gklarenberg** [comment]
We have very few blog posts this year on our website. Maybe add one on ResBaz, by @ha0ye @elisemorrison and @gklarenberg?

**Comment by elisemorrison** [comment]
Here's the hackmd page where notes will be taken: 
https://hackmd.io/jCaNzpNgS62_rVe99tpMvA?both
