### ISSUE TITLE
Agenda for board meeting 11-19-2019

### ISSUE THREAD

**Issue by vratchaudhary** [UF-Carpentry/Coordination#134]
- Spring instructor training workshop details

- November workshops' feedback review

- Spring workshops

- Spring social event

- UFII director meeting

**Comment by stuckyb** [comment]
I might suggest making item 2 a general debrief on the November workshops, just in case there are additional, non-feedback issues to discuss.

**Comment by vratchaudhary** [comment]
Travel grants
