### ISSUE TITLE
Agenda for board meeting on Tuesday Jan 28th at 02:30 PM

### ISSUE THREAD

**Issue by vratchaudhary** [UF-Carpentry/Coordination#139]
1. Approve minutes from the last meeting
2. Final check on Spring social prep
3. Instructor training
4. IFAS funding and ideas to use those funds
5. Social science workshop
6. Updates on geospatial modeling workshop
7. USDA machine learning workshop

**Comment by evebohnett** [comment]
8. Neon workshop (a rep is joining the meeting so earlier in schedule is better)

**Comment by stuckyb** [comment]
9. Financial hardship survey as part of workshop registration (update from BJS and discussion).
