### ISSUE TITLE
update instructor training webpage

### ISSUE THREAD

**Issue by stuckyb** [UF-Carpentry/Coordination#142]
Before sending out workshop announcements, we need to update https://www.uf-carpentries.org/training/.

**Comment by vratchaudhary** [comment]
Other issues:
1. Overview of feedback for social science workshop
2. Instructor training
3. Board member elections 
4. Geospatial workshop
5. Rec workshop
6. Sponsorship, need to start thinking about sponsors- UFBI, museum, email solicitations- something to think about.

**Comment by stuckyb** [comment]
Page is updated.
