### ISSUE TITLE
March 17, 2020 meeting agenda

### ISSUE THREAD

**Issue by stuckyb** [UF-Carpentry/Coordination#143]
* Approve minutes from March 3, 2020 board meeting: https://www.uf-carpentries.org/minutes/board-2020-03-03/
* Instructor training debrief
* Plan for upcoming workshops re: coronavirus
  * Geospatial
  * Genomics
  * UCF?
* Travel award re-submission
* Annual report (for IFAS, etc.) update
* Improved pre-workshop survey

**Comment by elisemorrison** [comment]
Under instructor training debrief, we could also discuss Carpentries membership

**Comment by elisemorrison** [comment]
Meeting minutes will be taken here: https://hackmd.io/-X9SNE41SXSM_quy3KNDOQ?both
