### ISSUE TITLE
March 31, 2020 meeting agenda

### ISSUE THREAD

**Issue by stuckyb** [UF-Carpentry/Coordination#144]
* Approve minutes from March 17, 2020 board meeting: https://www.uf-carpentries.org/minutes/board-2020-03-17/
* Geospatial workshop
  * Set date
  * Decide on fees
  * Registration limit
  * Technology plan
  * Resources for teaching online carpentries workshops
* Genomics workshop: canceled
* UCF update
* Custom pre-workshop survey
  * Possible to modify affiliation question(s) through DOCE?
  * Question(s) about workshop fees?
* Travel awards: any additional action required right now?
* Annual report (for IFAS, etc.) update

**Comment by elisemorrison** [comment]
Meeting minutes will be taken here: https://hackmd.io/6KAa6aOgQSOq4PLW0b3--g?both
