### ISSUE TITLE
April 14th, 2020 meeting agenda

### ISSUE THREAD

**Issue by evebohnett** [UF-Carpentry/Coordination#145]
Approve minutes from the last meeting:

https://github.com/UF-Carpentry/website/blob/master/_minutes/Board-2020-03-31.md

* Geospatial meets NEON workshop 5/18 & 5/19 - free  -12 participants
- registration "pre-workshop survey"  link to add to the website
- online instructors call
- department listserv document (Everyone put the department contacts for one person to push to)
https://docs.google.com/document/d/1AyEg5_xJrdbIr1LF0aaSCUcHBKNFVlw0Yqf-TPo8fDk/edit

*REC workshop survey
-online workshops for REC can get members from all RECs or we can still choose one REC.

**Comment by elisemorrison** [comment]
Minutes will be taken here: https://hackmd.io/wX4uf_fgQj2UPs7h74apbQ
