### ISSUE TITLE
April 28th, 2020 meeting agenda

### ISSUE THREAD

**Issue by evebohnett** [UF-Carpentry/Coordination#146]
Approve minutes from the last meeting:
https://github.com/UF-Carpentry/website/blob/master/_minutes/Board-2020-04-14.md

*Geospatial meets NEON workshop 5/18 & 5/19 - free -12 participants
-instructor/moderator/helper signup
-registration pages
-website updates

*REC online workshop survey
-geospatial + special topic?
-dates June 15/16, June 22/23?

**Comment by stuckyb** [comment]
Very minor item for discussion: github integration on UF carpentries slack.

**Comment by gaurav** [comment]
@stuckyb I set up the GitHub/Slack integration in the first place, so let me know if you have any questions about that!

**Comment by stuckyb** [comment]
Thanks, @gaurav !

**Comment by elisemorrison** [comment]
Meeting notes will be taken here: 
https://hackmd.io/TyJuu48gQROakszPxfcmtw
