### ISSUE TITLE
Carpentries geospatial workshop at UW-Madison

### ISSUE THREAD

**Issue by MarconiS** [UF-Carpentry/Coordination#147]
The Carpentries community at UW-Madison offers a Geospatial Data Carpentry workshop on July. Because of high demand for the workshop they are working to offer this workshop online. The idea is recording a series of videos that mimics what we would do live - complete with live coding plus some "live" online time with participants to work through examples and some of the challenges.
Despite they have a few solid instructors at UW-Madison they asked me to reach out with the UF carpentries club in case anybody is interested in contributing. Let me know if you are interested and I can send you the contact of Dr. Sarah Graves who's organizing it there :)

Cheers!

**Comment by stuckyb** [comment]
Hi, @MarconiS -- just checking in on this issue.  Is UW still looking for instructors?  Has the workshop already happened?

**Comment by MarconiS** [comment]
Hi! I am not 100% sure anymore, but I guess they found all the folks for doing it, since I haven’t heard back any news. I think I can close the issue. Sorry for not having done it before!

On Jul 10, 2020, at 4:30 PM, stuckyb <notifications@github.com<mailto:notifications@github.com>> wrote:

[External Email]


Hi, @MarconiS<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_MarconiS&d=DwMCaQ&c=sJ6xIWYx-zLMB3EPkvcnVg&r=4VxGZUcfLYxHE04LCb8Ih4Rh5S6BLl7oYEqcH0ZDUmg&m=ECOm5encL68nAPRQDuL38hdi8K3_6uNi8ILp-XY3e9o&s=5bN9aOgXiEe9xwsJV64l5Q5J_9ZPgr7-ZB6VPXd823s&e=> -- just checking in on this issue. Is UW still looking for instructors? Has the workshop already happened?
