### ISSUE TITLE
June 16th board meeting

### ISSUE THREAD

**Issue by vratchaudhary** [UF-Carpentry/Coordination#150]
2:30-3:00 PM- board meeting to discuss:
Approval of meeting minutes: https://www.uf-carpentries.org/minutes/board-2020-06-02/

*REC workshop preparation new dates- 4day distributed workshop
*Reporting of UFCC stats to funders -Status and tasks etc

**Comment by evebohnett** [comment]
CarpentryCon @ Home
https://carpentries.org/blog/2020/06/call-for-carpentrycon-review-and-regional-hosts/
