### ISSUE TITLE
July 14 board meeting agenda

### ISSUE THREAD

**Issue by stuckyb** [UF-Carpentry/Coordination#151]
* Introductions
* Approve minutes from June 16, 2020 board meeting: https://www.uf-carpentries.org/minutes/board-2020-06-16/
* REC workshop debrief.
* Develop best practices procedures for security and safety of virtual workshops.  We can discuss:
  * Zoom features (waiting room, meeting password, etc.).
  * Registrations within Zoom or outside of zoom?
  * Email domain restrictions.
* Carpentries membership renewal (Brian will present some info/ideas).
* August workshops.
* Annual report.

**Comment by evebohnett** [comment]
Updates from Felipe
