### ISSUE TITLE
July 28 board meeting agenda

### ISSUE THREAD

**Issue by stuckyb** [UF-Carpentry/Coordination#152]
* Introductions
* Approve minutes from July 21, 2020 board meeting: https://www.uf-carpentries.org/minutes/board-2020-07-21/
* August workshops.
* Annual report.
* Possible short collaboration with chemometrics course (Brian).
* How do we approach potential sponsors this year?

**Comment by elisemorrison** [comment]
The meeting minutes will be live recorded here: https://hackmd.io/fPSOBZK9SaKVP_nwfNKH9g
