### ISSUE TITLE
Dec 1, 2020 Board Meeting

### ISSUE THREAD

**Issue by narayanibarve** [UF-Carpentry/Coordination#160]
- Introductions.
- Approve minutes from meeting on Nov 17th, 2020. 
- Update on sponsorship email. 
- Continuing the discussion on the "Introduction to R" proposed workshop to be held in the last week of January. 
- Chemometrics course update

**Comment by vijaybarve** [comment]
A quick tutorial on "How to post meeting minutes on our website"
