### ISSUE TITLE
April 27, 2021 Board Meeting

### ISSUE THREAD

**Issue by mstagliamonte** [UF-Carpentry/Coordination#170]
- Introductions
- Approve minutes from April 13 board meeting ( https://www.uf-carpentries.org/minutes/board-2021-04-13/ )
- Instructor training applications/selection of candidates
- Discuss the creation of additional roles within the DC governance, e.g. data master
- Any other business

**Comment by ktoddbrown** [comment]
UF NSF proposed Open Synthesis Data Center (NCODES) update
