### ISSUE TITLE
March 14th, 2022 Board Meeting Agenda 11am-12pm EST

### ISSUE THREAD

**Issue by audreyculver** [UF-Carpentry/Coordination#187]
March 14th, 2022 Board Meeting Agenda 11am-12pm EST

Agenda:
1. Introductions
2. Approve meeting [minutes ](https://www.uf-carpentries.org/minutes/)from Feb. 28th board meeting 
3. Update on Carpentries' new policy on use of logo 
4. Update on FY22 budget & membership tier
5. Update on sponsorship emails
6. Update on upcoming workshops
7. Discussion on documenting Chair & Secretary responsibilities on website or in charter
8. Any other business

**Comment by corybrunson** [comment]
Additional item:

* Document Chair & Secretary responsibilities on website or in charter?

**Comment by corybrunson** [comment]
Minutes are posted here:
https://www.uf-carpentries.org/minutes/board-2022-03-14/
