### ISSUE TITLE
2022 March 28 Board Meeting Agenda 

### ISSUE THREAD

**Issue by audreyculver** [UF-Carpentry/Coordination#188]
March 28th Meeting Agenda 11AM-12PM EST:

1. Introductions
2. Approve meeting [minutes](https://www.uf-carpentries.org/minutes/) from March 14th board meeting 
3.  Update on UF Carpentries' logo
4. Update on membership tier
5.  Update on sponsors
6. Update on upcoming workshops- websites, instructors, helpers
7. Update on report for IFAS
8. Discussion of soliciting interest for workshops
9. Continue discussion of set dates for Fall 2022 workshops
10. Any other business

**Comment by corybrunson** [comment]
Minutes posted [here](https://www.uf-carpentries.org/minutes/board-2022-03-28/).
