### ISSUE TITLE
Credit for iDigBio's support of the UF Carpentry Club

### ISSUE THREAD

**Issue by mjcollin** [UF-Carpentry/Coordination#2]
I have received input from the iDigBio PIs that since I am paid 100% off iDigBio, everything I do needs to credit iDigBio. They want to be acknowledged as having supported the creation of UF Carpentry and the workshops we've done. My perspective is that this has been a side project independent of my job although since it turns out they would have liked to have supported the effort, I should have given the opportunity to do so.

Independent of that debate, it turns out that Pam Soltis had asked Larry Page to contribute to the first Carpentry membership:

```
When Ethan White was trying to find sponsors for the Data Carpentry ‘membership’ at UF,
 we asked iDigBio.  In year 1, the solution was that iDigBio couldn’t pay directly so UFBI 
would pay double, and iDigBio would repay by paying for things for UFBI needed that 
iDigBio could pay for.  In fact, I didn’t ever ask iDigBio for the $3750.  For year 2, this 
discussion wasn’t held, so UFBI is paying $7500 to support Carpentries.

In a sense, perhaps iDigBio was supporting Data Carpentry at UF during 2016-17, but in
terms of supporting the organization and its workshops here, that isn’t currently being covered.
```
 Based on this I have put iDigBio on the list of sponsors. Also based on the number of sponsors, I want to move them to a separate page where they can be acknowledged how they like and I also want to stop trying to list them individually in workshop announcements etc and just point to the new page.

**Comment by ha0ye** [comment]
My only comment here is to acknowledge sponsors on a per-year basis: i.e. list the sponsors in each academic year. This seems like it would please the groups that have financially supported in the past with continued recognition, while also providing some incentive to continue supporting the organization.

**Comment by mjcollin** [comment]
I agree w/ Hao that per-year sponsorship is probably a good way to do this, linking to new site issue as a reminder. 

https://github.com/UF-Carpentry/website/issues/14
