### ISSUE TITLE
Abstract for CarpentryCon

### ISSUE THREAD

**Issue by justinmillar** [UF-Carpentry/Coordination#20]
Let's use this Google Doc to draft an abstract for CarpentryCon.

https://docs.google.com/document/d/1nJEdnsnXuwgSkGbNyBpiMByDR43M0WWp1Jtai7lO1l4/edit?usp=sharing

**Comment by justinmillar** [comment]
Some information from the CarpentryCon website:

- The length is limited to 150 words
- Presentations can be a poster, lightning talk, or both (it looks like lightning talks are ~5-8 minutes)
- Themes for presentations are:
  - Community building 
  - Teaching computational skills
  - Applying computational methods to research
  - Curriculum development
  - Research skills

The abstract submission link is https://carpentries.typeform.com/to/AImKAG
The website for the conference is http://www.carpentrycon.org/

**Comment by justinmillar** [comment]
Preparation checklist:
- [ ] Outline and draft abstract
- [ ] Request registration wavier
- [ ] Book plan ticket
- [ ] Book hotel
- [ ] Create poster

**Comment by justinmillar** [comment]
@mjcollin updating progress: 
I applied for a registration wavier based on my status as a full-time student and expressed that any financial assistance would directly support additional Carpentry activities as the club is supporting my attendance. 

I believe I was able to get a room in the UCD dorms, they processed my payment so it seems like there was still room. I'll update if something changes. 

For the flight, I can fly out of Tampa (Orlando might be possible, but I strongly prefer to fly from Tampa). Based on the conference itinerary, I should I arrive on Tuesday May 29th. I could depart could Friday evening, but I wasn't finding any flights that departed late enough so I am expecting a Saturday departure. Based on this I requested 4 nights at the dorm. Here is what I've found on Google Flights so far https://goo.gl/flights/3drNi.

**Comment by justinmillar** [comment]
I have created a draft of the abstract in the Google Doc (link in first post). We will be entering under the "Community Building" theme. There is some logistic information that needs to be filled in from our records (# of workshops, attendees, instructors trained). Please note that the abstract is limited to 150 words.

Any and all feedback is much appreciated. If you prefer to not comment on the Google Doc please feel free to email me directly. Thanks!.

**Comment by mjcollin** [comment]
I left some comments and I suggest asking for a talk and poster - too much to say in 5 minutes and a poster gives you something to refer people to whom you might meet. I'm pretty sure UF is one of less than 10 places world-wide with this level of organization and may be unique in that it's not lead by a central authority. I hope people are interested in hearing about that.

**Comment by justinmillar** [comment]
Thanks everyone for your comments. I've integrated the feedback into an updated draft, which I will submit tomorrow (April 20th) at noon. I will be submitting for both a talk and a poster. If you have any additional comments, or would like more time to review please send me an email. Thanks again!

**Comment by fmichonneau** [comment]
+1 for asking for both poster and talk. This looks great!

**Comment by mjcollin** [comment]
+1 LGTM

**Comment by fmichonneau** [comment]
lighting talks schedule: https://github.com/carpentries/carpentrycon/blob/master/program/lightning-talks.md

poster schedule: https://github.com/carpentries/carpentrycon/blob/master/program/posters.md

Not officially (i.e., not linked to the main website) announced yet.

**Comment by justinmillar** [comment]
Here is a link for the presentation: https://docs.google.com/presentation/d/1j1cAIPeoU4J04eXQEm2p07NS99131OOoPnefKSS2yPk/edit?usp=sharing 

and the poster: https://docs.google.com/presentation/d/1o3O9tA9mTtHWh7r7s6AVRmSp-1SEt_EQUkbvwV6Y3Uc/edit?usp=sharing

**Comment by KristinaRiemer** [comment]
I think it would be useful for @justinmillar to attend the Library Carpentry talk by Kayleigh Lino (https://github.com/carpentries/carpentrycon/blob/master/Sessions/2018-05-30/08-Lightning-Talks-Session-2/1-abstract-kayleigh-lino.md), both for UF's involvement with the library generally and for myself personally.

**Comment by mjcollin** [comment]
RE presentation 

-  I think the fonts are too small throughout, especially for the light-on-dark theme which is often harder to read
-  I added my headshot
-  My thought on the key to our success is that the involved people are not assigned by or beholden to any formal authority, rather the authorities have just given us $/support and said "do your best". Of course they picked some great people to say that to which certainly helps.

**Comment by mjcollin** [comment]
Closing due to event having happened. @justinmillar Link to final presentation here?

**Comment by justinmillar** [comment]
Links:
Poster: https://uf-carpentry.github.io/carpentrycon2018/CarpentryCon-Poster.pdf
Talk: https://uf-carpentry.github.io/carpentrycon2018/CarpentryCon-presentation.pdf
