### ISSUE TITLE
2023 April 4 Board Meeting Agenda

### ISSUE THREAD

**Issue by cjcampbell** [UF-Carpentry/Coordination#206]
Introductions
Approval of [March 22th, 2023 minutes](https://www.uf-carpentries.org/minutes/board-2023-03-22/)
Approve March 7th, 2023 minutes, make sure they are posted
Debrief of Git workshop (Cory and Dellena). Some discussion items include:

- Lunch options
- In-person workshop notes [Corrected Link for board members](https://docs.google.com/document/d/10nxXuT7vP6mCnJDmebTqpHbKGD8JfO3IBqxbvJuHgDo/edit?usp=sharing)

Plans for upcoming Genomics workshop
Decide on Fall 2023 workshop docket, determine order, prepare to schedule
Sponsorship emails (Audrey)
Instructor trainings
New board member election process
Any other business

**Comment by corybrunson** [comment]
I finally have a minor IFAS report update. More should be forthcoming this semester.

**Comment by corybrunson** [comment]
Another item for the next agenda: We should take photos at events to put on the website and post on social media!

**Comment by corybrunson** [comment]
Minutes are posted [here](https://www.uf-carpentries.org/minutes/board-2023-04-04/).
