### ISSUE TITLE
Registration process for 3rd instructor training

### ISSUE THREAD

**Issue by mjcollin** [UF-Carpentry/Coordination#3]
Instructor training 3 is to be on March 5 & 6. I propose using an application process as the wait list already has about 10 people on it. Maneesha needs the registrants in the next 2 weeks:

> You can certainly do a selective application process.  If you have people fill out our application (https://amy.software-carpentry.org/forms/request_training/) using the group code:  2018-03-05-UF-ttt
I can filter applications for you and send you a csv for you to review.  From there you can let me know who you want to accept.  To give time for all that, I'd suggest closing applications by Feb 9, and making decisions by Feb 14.   We want people to have a couple of weeks to prepare for the event -- some short reading and reviewing our lessons.

> If you want to use your own application process that's fine -- I'd just want to have names by mid-February.

Do we want to make our own form or use theirs?

**Comment by ha0ye** [comment]
I see no problem with using that form.

**Comment by Cactusolo** [comment]
Agree with @ha0ye 

_I checked their form, pretty robust and informative, unless we want extra infor aside that._

**Comment by KristinaRiemer** [comment]
I think this form is fine too.

**Comment by KristinaRiemer** [comment]
@mjcollin what's the cap for instructor training?

**Comment by stuckyb** [comment]
I agree with the  -- I think the default SC form looks fine!

**Comment by KristinaRiemer** [comment]
As per group consensus, we'll use the Carpentries application form. The application will be closed on February 9 and then we'll have until Feb 14 to pick attendees from that. 

We should advertise this widely, starting with the informatics listserv and I'll send it out to Wildlife department. Other suggestions for where/how to advertise?

**Comment by ha0ye** [comment]
Not to exclude grad students, but there is a weekly UF Postdoctoral Newsletter that sometimes includes instructional training events: http://postdoc.aa.ufl.edu/newsletter/submission-guidelines/

**Comment by mjcollin** [comment]
@KristinaRiemer - The UFII holds 24 so let's cap it at that.

@picardis - Are there others at FLREC that would be interested in applying?

I think this decision is made and we can discuss applications when they're in. Opening #4

**Comment by picardis** [comment]
I am going to advertise to people here at FLREC as well.

**Comment by ha0ye** [comment]
Some thoughts after seeing the responses:

* add a category for previous teaching experience for TA (different folks seemed to select all 3 of the options that weren't "none" for this)
* splitting the "why do you want to attend" into more explicit questions about rationale, is it for teaching credentials, is it to have the certification to teach Carpentry workshops, is it to improve pedagogy skills in general?

**Comment by KristinaRiemer** [comment]
@ha0ye I 100% agree with a specific question to determine if applicants intend to teach Carpentry workshops. It seems like from some of the responses that some people just want some general training in teaching computational skills.
