### ISSUE TITLE
Date for mid-semester fall 2018 workshop

### ISSUE THREAD

**Issue by mjcollin** [UF-Carpentry/Coordination#30]
The iDigBio summit is Oct 1-3 so having a workshop on Oct 4-5 would be convenient for one of our sponsors.

We'd (iDigBio) would be interested in a 1 day or in trialing a new lesson based on natural history data. We also need to look at the football schedule.

**Comment by gklarenberg** [comment]
Home game against LSU on Sat the 6th...

**Comment by mjcollin** [comment]
Just looked, the LSU football game is home that weekend so perhaps this is a terrible date especially since our remote summit attendees will have a hard time getting a room unless we did a one day workshop.

**Comment by jenningsdt** [comment]
Agreed - a 1-day workshop is probably the only feasible solution if we want to do it in association with the Summit.

**Comment by mjcollin** [comment]
A "day of R" is and good idea and the club can provide some support.

**Comment by mjcollin** [comment]
@debpaul We talked about this today at the board meeting (with David attending) and everyone would be happy to do our standard playbook for a 1-day workshop on the Thursday after the summit. We'd offer seats to Summit attendees first and David will look in to whether idb can just pay for them. At some point we'd open the workshop to the general UF audience.

For materials we thought of just doing one day of R with perhaps an ridigbio 30 minute section at the end instead of the sqlite section. Do you think you can get the natural history R lesson designed (with input from others including myself) for this? Would you rather just do ecology?

I've emailed UFII to reserve the classroom.

**Comment by mjcollin** [comment]
Still waiting for confirmation of room, Flora says other have speculative holds on the room and she's trying to confirm with them.

Larry and Pam (iDigBio & Biodiversity Institute) are willing to pay for any participants who attend as part of the iDigBio Summit so there will be more motivation for their participation and no impact to us financially.

**Comment by jenningsdt** [comment]
Thinking out loud about the curriculum:

Option 1 -- Do the Data Carpentry R lesson using either the Ecology or Nat Hist dataset, except replace SQL with ridigbio

Option 2 -- Replicate this recent workshop: https://uf-carpentry.github.io/2017-08-18-Marston-RDay/

Option 3 -- ???

**Comment by debpaul** [comment]
Hi All,

If we were going to do geospatial, we could also do this lesson:
https://data-lessons.github.io/QGIS-nhcdata-lesson/

We first did this lesson at a Georeferencing for Research Use Workshop 
in 2016. It is written by a graduate student from UCSB. It's focus is on 
visualizing data to assess its fitness for use and to spot/fix data 
quality issues.

Best,
Deb


On 2018-06-21 2:26 PM, Justin Millar wrote:
>
> Another option could be to cover some of the material in the 
> geospatial data lesson 
> <https://urldefense.proofpoint.com/v2/url?u=http-3A__www.datacarpentry.org_lessons_-23geospatial-2Dcurriculum&d=DwMCaQ&c=HPMtquzZjKY31rtkyGRFnQ&r=ODXYRdWm1Oqf5-w5G2NjQw&m=LkYlYZm3MX9y-XpwSohFJbxDBlvLeQyFY3UlNO3Pp_4&s=neAsscpeGJD9XmWBcDEuXsP29YQcdiHVggWYDp08jow&e=>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_UF-2DCarpentry_Coordination_issues_30-23issuecomment-2D399199363&d=DwMCaQ&c=HPMtquzZjKY31rtkyGRFnQ&r=ODXYRdWm1Oqf5-w5G2NjQw&m=LkYlYZm3MX9y-XpwSohFJbxDBlvLeQyFY3UlNO3Pp_4&s=NBOtoKcNKTI53NLlvY4ew9FhJE1yejh74ECZGnUE1tA&e=>, 
> or mute the thread 
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AC2gSwAjbPNO7yi46T85Tiehulkw5UXHks5t-2D-2DU7gaJpZM4UmTea&d=DwMCaQ&c=HPMtquzZjKY31rtkyGRFnQ&r=ODXYRdWm1Oqf5-w5G2NjQw&m=LkYlYZm3MX9y-XpwSohFJbxDBlvLeQyFY3UlNO3Pp_4&s=_Q-km97ruqTgnZtqvYPp1u_LAByaLzxbPPKCtup-rD8&e=>.
>

-- 
-- Upcoming iDigBio Events https://www.idigbio.org/calendar
-- Deborah Paul, iDigBio Digitization and Workforce Training Specialist
iDigBio -- Steering Committee Member
SPNHC Liaison, Member-At-Large and Member International Relations Committee
SYNTHESYS3 Representative
Institute for Digital Information, 234 LSB
Florida State University
Tallahassee, Florida 32306
850-644-6366

**Comment by mjcollin** [comment]
Date selected, superseded by #33 for actual workshop planning.
