### ISSUE TITLE
Make new logo

### ISSUE THREAD

**Issue by mjcollin** [UF-Carpentry/Coordination#31]
The new Carpentries logo offers an opportunity for us to make our own derived one. Hao (IIRC) suggested adding a few teeth and an eye to the wrench to make a gator. Probably changing the color to green or maybe the bolt to UF orange or something would look good.

The logo is probably trademarked like the old one. Design up an example and forward to Tracy & Ethan for their review and approval before using.

https://software-carpentry.org/blog/2018/02/our-new-logo.html
https://software-carpentry.org/license/

**Comment by Cactusolo** [comment]
I like Hao's (IIRC) idea! Pretty intuitive, and easy to link to the key elements!

**Comment by gklarenberg** [comment]
Is there a vector file available anywhere? The logo from the website downloads as a png

**Comment by fmichonneau** [comment]
All the carpentries logos are in this repo: https://github.com/carpentries/logo/

**Comment by mjcollin** [comment]
From the license issue on that repo they're thinking of cc0 with Python's trademark language, a quote:

"Any use of a derived (modified) logo for any commercial purpose must also be approved first by the PSF. We will generally be unable to do this, because of the confusion it may cause. As a guideline, modifications that leave the shape -- but not necessarily the colors -- unaltered are likely to be approved. Inclusion of other visual elements at an offset to the logo is generally acceptable (subject to other terms of this policy). Modifications that modify or obscure any part of the shape of the logo will not be approved."

So we'll have to do a mock up and ask permission.

**Comment by KristinaRiemer** [comment]
Sorry for not doing this yet @mjcollin, I was waiting for the green light in https://github.com/carpentries/logo/issues/2 to reach out to UF's service. I didn't want to waste anyone's time pre-emptively.

**Comment by tracykteal** [comment]
As per https://github.com/carpentries/logo/issues/2#issuecomment-413245409 you can develop a derived logo. Since we don't have all the guidelines developed yet, we can check in this issue for this particular case. Looking forward to the UF Carpentry Club logo!

**Comment by KristinaRiemer** [comment]
Thanks @tracykteal!

**Comment by KristinaRiemer** [comment]
@mjcollin would this be considered an IFAS related project?

**Comment by KristinaRiemer** [comment]
Another question for @mjcollin: is the club considered a student group? I wouldn't think so, but...

**Comment by mjcollin** [comment]
No, we're not an official student organization at UF.

**Comment by ha0ye** [comment]
@elisemorrison sent out draft versions to the board. Current status is:
* check with UF rules on branding (someone we can email in University Relations)
* send out any edits/updates for discussion (email or slack)
* voting by the board (next meeting)

**Comment by gaurav** [comment]
It looks like the Carpentries are still sorting through trademark and logo reuse policies: https://github.com/carpentries/logo/pull/6#issuecomment-492431362

**Comment by ha0ye** [comment]
If the board has decided on a logo, I think we should just post it to the Carpentries logo repo as an issue for checking.

**Comment by tracykteal** [comment]
Yes, that would be a great approach. Thanks!
