### ISSUE TITLE
1-day Workshop Thurs Oct 4th 2018

### ISSUE THREAD

**Issue by mjcollin** [UF-Carpentry/Coordination#33]
We'd like to do a workshop in coordination with iDigBio on 10/4/2018. The UFII has been booked already. See #30 for history on selecting this date. Need to identify an organizer and select curriculum.

**Comment by gklarenberg** [comment]
Would be happy to be an instructor, not sure about being an organizer (will have a better idea of my schedule the next few weeks/months by next month). I'd be keen to do some geospatial teaching as suggested by @justinmillar in #30

**Comment by mjcollin** [comment]
I can be organizer for this since I'd like it to tie to the iDigBio summit if possible.

**Comment by mjcollin** [comment]
Closing in favor of #51
