### ISSUE TITLE
Res Baz Logistics

### ISSUE THREAD

**Issue by ha0ye** [UF-Carpentry/Coordination#36]
- [ ] food / drink
- [ ] physical space for Friday events

**Comment by mjcollin** [comment]
![img_20180717_160947285](https://user-images.githubusercontent.com/1640727/43483086-95ae0136-94d8-11e8-91a3-7e482479324e.jpg)

**Comment by PunamA** [comment]
have submitted a request for McCarty C room 100 or a large room in CSE to fit at least 60

**Comment by gklarenberg** [comment]
Can someone post an overview of events + times + locations? Is there a final list of instructors and helpers for the R and Python workshops? The github pages still say TBD. 
Or is it somewhere out there on Github but I just haven't found it?

**Comment by ha0ye** [comment]
I can put this together for the speakers and panel. (Just got back from fieldwork.) I think Punam and Simona will have the list of instructors for the workshops. I’ll let @justinmillar decide on the timing for the mini-tutorials.

**Comment by KristinaRiemer** [comment]
@gklarenberg, now that the R workshop instructors and content have been decided, I imagine @picardis will update the workshop website when she gets a chance.

**Comment by KristinaRiemer** [comment]
Flora just told me that there are currently 22 people registered for Friday.

**Comment by stuckyb** [comment]
Thanks, Kristina.  Now it is 23.  :-)

**Comment by gklarenberg** [comment]
So who is going to be at Cypress and Grove tonight to be officially hosting?

**Comment by ha0ye** [comment]
No official hosting, @KristinaRiemer will be there, but if you just want to set up a table or whatever, that’s sufficient, IMO.
