### ISSUE TITLE
ResBaz Social Mixers

### ISSUE THREAD

**Issue by ha0ye** [UF-Carpentry/Coordination#39]
- [ ] plan icebreakers
- [ ] finalize date and time
- [ ] food / drinks / ice cream?
- [ ] coordinate with more regular meetups during the semester (e.g. Hacky Hours?)

**Comment by PunamA** [comment]
One of the social mixers can possibly be hosted by the r-ladies @gklarenberg

**Comment by gklarenberg** [comment]
Yes @PunamA - that's a great idea

**Comment by ha0ye** [comment]
Scheduling done, keep it all informal and after day is over.
