### ISSUE TITLE
ResBaz Data Carpentry (R)

### ISSUE THREAD

**Issue by ha0ye** [UF-Carpentry/Coordination#40]
- [x] find instructors
- [x] find helpers
- [x] set up website
- [x] announce and recruit attendees

**Comment by justinmillar** [comment]
I'm always down for the R stuff, I can help with any/all of these.

**Comment by KristinaRiemer** [comment]
I can teach any of the DC material except OpenRefine, but can only teach on Thursday (day 2 of the workshop?). I can also be the organizer.

**Comment by picardis** [comment]
Workshop website is set up https://picardis.github.io/2018-08-15-ufii/
as well as etherpad https://pad.carpentries.org/2018-08-15-ufii

I'm having some issues with the syllabus on the website that still shows the software carpentry material. If I can't solve it by tonight I'll ask for help.

**Comment by PunamA** [comment]
hi all, i've sent out the emails for registration to the waiting list for both workshops. Alethea and Flora have sent the email to grad and post-doc list-servs so they should be sent out very soon.

**Comment by PunamA** [comment]
@picardis did you notify the carpentries about the workshops?

**Comment by picardis** [comment]
I did! I'm waiting on hearing back from Sher about the survey links. 

I also received a couple inquiries from people that wanted to sign up for the workshop and I sent them the link.

**Comment by PunamA** [comment]
@KristinaRiemer, Just checking if you are good and enroute to UF campus?

**Comment by KristinaRiemer** [comment]
@PunamA I'm not coming to Gainesville until tomorrow morning, that's why I asked if I could teach on Thursday. I'm doing SQL Thursday afternoon.
