### ISSUE TITLE
ResBaz Software Carpentry (Python)

### ISSUE THREAD

**Issue by ha0ye** [UF-Carpentry/Coordination#41]
- [x] find instructors
- [x] find helpers
- [x] set up website
- [ ] announce and recruit attendees

**Comment by gklarenberg** [comment]
@PunamA I'd be interested in helping. By no means a Python guru but could do the introductory bits

**Comment by PunamA** [comment]
@ha0ye @mjcollin @picardis @gklarenberg I was just thinking, isn't the day 1 for python and R workshops the same? i.e. Day 1: "Data organization in spreadsheets", "SQL for data management" then Day 2: "Data visualization in R or Python". So it would mean we duplicating the teaching?

**Comment by PunamA** [comment]
Or sorry is it software carpentry workshops that we would be doing for Python?
http://swcarpentry.github.io/python-novice-inflammation/
http://swcarpentry.github.io/python-novice-gapminder/

**Comment by ha0ye** [comment]
I think it's whatever you want to do. Though I agree it makes sense to diversify some of the teaching materials if the lesson content still works for people. (e.g. unix shell, Git)

**Comment by Cactusolo** [comment]
I support this idea.

Miao

**Comment by PunamA** [comment]
Hi all, please see the webpage for the Python workshop. Let me know if this is ok. it is based on the same schedule used last year:
https://punama.github.io/2018-08-13-uf/

PS: I apologize for the wrong date. I didn't realize but I'll change this to the correct date once I get feedback from folks :) 
I was thinking to send out call for instructors for both Python and R workshops tomorrow.
Once this schedule is agreed I'll also move forward with advertising to UF campus.

NOTE: the lecture would be Software carpentry I believe.

**Comment by ha0ye** [comment]
How about Day 1: unix and Git; Day 2: Python. (It looks like the python lesson is slated at 6 hours, which going by typical carpentry time estimates is a rather optimistic underestimate.)

**Comment by Cactusolo** [comment]
Hi guys,

I have workshop today and tomorrow at UFBI. So I’m not able to come to board meeting. 

And Flora reminded me that for our August workshops (two places?! One is UFII E252, where is the other?), she have not received any confirmation and registration yet. I suggest we need to discuss this and confirm with her in the coming board meeting.

Thanks!


Dr. Miao Sun

Post-Doc Associate, Solti Lab
Florida Museum of Natural History
Dickinson Hall, 1659 Museum Road
University of Florida, Gainesville, FL 32611, USA

Phone:  (352) 284-0928
Email: cactus@ufl.edu; cactusresponsible@gmail.com

**Comment by PunamA** [comment]
that's a good point. I also like the idea of having Python be an entire day. I have updated the schedule to reflect this along with links to the lessons.

**Comment by PunamA** [comment]
@Cactusolo I believe R will be held in UFII room and Python in the Martson Library room on the lower ground floor (not sure the room number). Is that right @mjcollin ?

**Comment by PunamA** [comment]
Hi all, regarding the rooms. I Called up the manager for the CSE building. It turns out that we are not allowed to book the room during the semester break. The manager mentioned something about no staff, and that being the time that they renovate the room etc. He recommended that I book the rooms on the first floor CSE 119 or CSE 121. I have put in a request for the room with @mjcollin  as the adviser :) I'll follow up on that later today to make sure it went through. He also advised that technically you aren't allowed to eat in these rooms. But as long as you clean up well he said what they don't know won't hurt. So if having too many people being catered for in UFII is too much we can split the lunches between the two places.

**Comment by PunamA** [comment]
Hi all, they have confirmed room CSE220 which is on the second floor of the Computer Science building next to UFII for the Python workshop.

**Comment by ha0ye** [comment]
Looking st the photos of the room online, we might want to bring the registration limit down to 24 seats if we can.

**Comment by PunamA** [comment]
Online they say that the room fits up to 50. Alternatively, I can ask if they can just give us CSE 119 for August 15 and 16th as well.
