### ISSUE TITLE
ResBaz mini-tutorials

### ISSUE THREAD

**Issue by ha0ye** [UF-Carpentry/Coordination#43]
1-2 hour focused tutorial sessions on simple or advanced topics
- [ ] find folks to teach
- [ ] brainstorm possible topics

Some possibilities:
* data viz, animations, maps (leaflet?)
* binder
* git / reproducible workflows
* preprints
* OSF
* data management / curation
* github pages

**Comment by justinmillar** [comment]
Some other ideas
- Shiny
- writing functions
- writing for loops
- blogdown
- purrr/functional programming

**Comment by ha0ye** [comment]
@justinmillar Can you go ahead and start a google sheets schedule for people to sign up to lead sessions? It'd be great to have some info ahead of time for the website.

**Comment by Cactusolo** [comment]
@justinmillar I'm happy to introduce these two:
+ writing functions
+ writing for loops

**Comment by justinmillar** [comment]
https://docs.google.com/spreadsheets/d/1pHXzTMU7QM8D10vA7Gcfmzf2s7BhTflA3LGlsIyOrLs/edit?usp=sharing

**Comment by KristinaRiemer** [comment]
Would a session on literate programming with R Notebooks be of interest to people? I could demo that.

**Comment by justinmillar** [comment]
### Friday Mini Lessons

Topic | Room | Instructor | Description
--- |---|---|---|
loops/functions | UFII classroom | Miao | A crash course on writing for loops and functions in R
Binder | UFII Conference Room | Hao | ???
Dates | CSE E220 | Ben | Demystifying dates in R with the lubridate package
Blogdown | CSE E221 | Justin | Make your own website with a blog all in R!
Reproducible Research | CSE E119 | Geraldine | ???  

@ha0ye @gklarenberg add short description

**Comment by gklarenberg** [comment]
An Introduction to Reproducible Research: version control, sharing, publishing and archiving
(does that sounds okay?)

**Comment by ha0ye** [comment]
@gklarenberg Sounds good to me. Do you want to me emphasize that it's more of a discussion / Q&A around practices rather than a full lesson (based on our brief conversation about it)?

**Comment by gklarenberg** [comment]
I can probably fill up an hour with a presentation, some of the git stuff and a "tour" of repositories etc that are out there (at least). But if anyone has any examples that they can/want to showcase, that'd be awesome :)

**Comment by ha0ye** [comment]
I'll put a call out to my lab to see if they can help out. 👍

**Comment by fmichonneau** [comment]
happy to help as well. There is some material that could be useful here: http://www.datacarpentry.org/rr-workshop/

**Comment by KristinaRiemer** [comment]
Hey @gklarenberg, I have all the code in a GitHub repo (https://github.com/KristinaRiemer/MassResponseToTemp) for a project that I had published in eLife (https://elifesciences.org/articles/27166) earlier this year. It's set up so that someone should just be able to run the `repro_run.sh`script on the command line to reproduce all of the data download, cleaning, analysis, and viz. I've included all the instructions in the README.

**Comment by gklarenberg** [comment]
@KristinaRiemer Oooooh, very cool! Maybe I can use it to show people how to fork-clone etc and then run it? How long does it take to run?

**Comment by gklarenberg** [comment]
@fmichonneau That'd be great. I'm using a presentation Naupaka Zimmerman did at the NEON course I did this summer - which is made from stuff you, Jenny etc have been doing: http://neonscience.github.io/slide-shows/intro-reprod-science.html (I've been trying to change the slides in the .md file but can't get it to produce slides for me. I've never done that before so maybe I am doing something wrong)
