### ISSUE TITLE
Renewal process for Carpentry membership

### ISSUE THREAD

**Issue by mjcollin** [UF-Carpentry/Coordination#5]
Issue for the process of renewing the Carpentry membership.

Contacted by Jonah to sign letter acknowledging the institution we have an agreement with is changing (see attached). MJC is signing on behalf of the club for expediency but he's asked for a long-term contact name.

Renewal will be due early summer.

**Comment by Cactusolo** [comment]
Is there ** an attachment ** to be expected?

**Comment by mjcollin** [comment]
[uf.edu_signed.pdf](https://github.com/UF-Carpentry/Coordination/files/1696975/uf.edu_signed.pdf)

Sorry about that.

**Comment by mjcollin** [comment]
Hello Matthew,

I don't believe that we have 'met' yet; I am the business administrator for The Carpentries. Since University of Florida's membership will be expiring in a few months, I want to check in with you about how things are going generally and see how you are feeling about renewal. It would be great to have University of Florida join The Carpentries for another year of membership. 

Please let me know if you have any questions or concerns, and if you know you would like to move forward with renewal, I would be happy to get that started!

Best,

Elizabeth Williams

**Comment by mjcollin** [comment]
Update on the exact date (note that I don't concur with the "plenty of time" part, these things take months.)

Hello Matthew,

Thank you for the update! The current agreement will not end until 8/15/2018, so there is still plenty of time. 

Please let me know if I can answer any questions or provide anything!

Best,

Elizabeth Williams

**Comment by mjcollin** [comment]
Emailed today to ask her to work with Alethea about an invoice and PO for payment.

**Comment by mjcollin** [comment]
Carpentries is still getting set up as a vendor in UF's system so they can be paid. Otherwise, that's the last step before the PO is issued.

**Comment by mjcollin** [comment]
Alethea updated today:

Just as an update for this. I have the PO submitted for the membership dues, and am just waiting for it to go through the approvals.

**Comment by mjcollin** [comment]
Yesterday: 

Greetings everyone, 

I just wanted to update the contract issue has been resolved and the invoice for the membership sent by Elizabeth. 
It takes a few days to hit our financial systems, but I will let everyone know when the payment has been put through so you all can rest assured your membership has been renewed. 

As always, just let me know if you have any questions. 

Thanks, 
Alethea

**Comment by mjcollin** [comment]
Althea confirmed invoiced paid. Signed agreement in Google drive folder.
