### ISSUE TITLE
Reminder message/announcements about Board elections (Fall 2018)

### ISSUE THREAD

**Issue by ha0ye** [UF-Carpentry/Coordination#50]
See [board meeting notes](https://www.uf-carpentry.org/minutes/board-2018-08-28/) for discussion.

**Comment by ha0ye** [comment]
Hi everybody,

Here's a sample message / reminder. Feedback and/or suggestions are welcome (though note that we want to send this out tomorrow, so that there's time for another reminder next week before the deadline).

===
Subject: Interested in learning or teaching computing skills at UF? Sign up to be on the 2018-19 Carpentry Club board!

Message:
The UF Carpentry Club is looking for 7 board members for the new academic year (Sept 2018 - Aug 2019). **You don't have to be an expert programmer or experienced teacher to apply!** As long as you have an interest in building a inclusive and supportive culture for learning computing skills at UF, your voice is welcome. Anyone who is at UF and has participated in a Carpentry event in the past 2 years is eligible.

We are specially interested in input from community members who want to see particular lessons taught (such as the new geospatial content), want to further our engagement with like-minded groups (such as UF Data Science and Informatics and R-Ladies Gainesville), or want alternative kinds of events (such as the recent panel discussion on non-academic careers in data science at ResBaz Gainesville).

The deadline for self-nominations is **September 10**, and you can self-nominate at https://docs.google.com/forms/d/e/1FAIpQLSf4Sk0m8NuE28kToUaWdVNYuyQpRGkbz5059qJITQm4hGKthw/viewform?usp=sf_link

To read more about the elections and the club, visit our web site: https://www.uf-carpentry.org/elections/

**Comment by mjcollin** [comment]
Did anyone send a reminder? Today is an auspicious day for doing so and I can either send it or work with someone to get them the instructor list: https://github.com/UF-Carpentry/workshop-data

**Comment by ha0ye** [comment]
I sent one last week, but yes, another one today or tomorrow, emphasizing last chance and Monday deadline is ideal. Can I re-up to informatics-teaching-L and have you additional redistribute to the instructor list?

**Comment by mjcollin** [comment]
Sure, re-send to informatics-teaching-l and I'll re-send to the 5-7 people who are not on the list.

**Comment by gklarenberg** [comment]
The nomination instructions say to submit a statement < 300 words. However, the nomination page does not accept anything more than 800 characters. That's only about 100-150 words (less if spaces are also counted as characters - which it does). Help? 
Disclosure: I'm trying to submit a self-nomination.

**Comment by gklarenberg** [comment]
So @ha0ye 800 characters it is then? Maybe that could be changed in the nomination instructions as well?

**Comment by ha0ye** [comment]
I think @mjcollin controls the google form.

**Comment by mjcollin** [comment]
Changed to 1500 chars which is probably much closer to the 300 words. We wanted it to be short to reduce effort but making it too short I think biases it towards people everyone knows already since new people can't pitch themselves successfully. Changing it mid-application is also not fair but I think we'll just have to accept it.
