### ISSUE TITLE
[October 4 workshop] confirm lesson content and instructor/helpers

### ISSUE THREAD

**Issue by ha0ye** [UF-Carpentry/Coordination#51]

**Comment by mjcollin** [comment]
Based on the available instructors and helpers, I think it's best to stick with the R ecology lesson. The 23-24 workshop would be great to try out the geospatial lessons since we wouldn't have to figure out how they work in order to cut them to one day.

**Comment by fmichonneau** [comment]
The spreadsheet lesson + R ecology should fit nicely in 1 day.
