### ISSUE TITLE
[October 23/24 workshop] confirm lesson materials and instructors/helpers

### ISSUE THREAD

**Issue by ha0ye** [UF-Carpentry/Coordination#52]

**Comment by fmichonneau** [comment]
let me know if you are interested in doing a Data Carpentry Geospatial workshop (http://datacarpentry.org/geospatial-workshop/). It was released yesterday!

**Comment by gklarenberg** [comment]
I would be very excited about that. Do we have *any* idea how many people would be interested in taking that?

**Comment by ha0ye** [comment]
On the day that the new material was announced, I sent an email to the board about it, @fmichonneau mentioned it here, and Ethan White tweeted about hoping we run a workshop on it soon... so yes, I think there's interest. :laughing:

**Comment by fmichonneau** [comment]
As a follow-up, we are organizing onboarding session for certified instructors interested in teaching this new material. You can sign up here: https://pad.carpentries.org/geospatial-onboarding I see @justinmillar has already signed up, but maybe others are also interested in doing so?

**Comment by ha0ye** [comment]
@MarconiS mentioned interest in teaching the new geospatial lessons.

**Comment by mjcollin** [comment]
Can you create a web site and link it on the uf-carpentry.org site in the event? Also, don't forget this document is here, I haven't ported it to the new site yet:

https://github.com/UF-Carpentry/Coordination/wiki/Organizing-a-Workshop

**Comment by ha0ye** [comment]
My preference is to keep some of the organizing instructions off of the website - the wiki is easier to edit, and while there's nothing wrong with operating transparently, I think having some divide between inward-facing docs and outward-facing docs is useful. (same goes for e.g. board member onboarding guide)

**Comment by justinmillar** [comment]
@gklarenberg The registration link was just finalized, and I sent the announcement email to the people on the waitlist.  We'll start advertising publicly on Monday.
