### ISSUE TITLE
Coordinate with Dan Maxwell about possible library internship position

### ISSUE THREAD

**Issue by ha0ye** [UF-Carpentry/Coordination#55]
See [board meeting notes](https://www.uf-carpentry.org/minutes/board-2018-08-28/) for discussion.

**Comment by gaurav** [comment]
The relevant section from the notes is:
> - library internship (10hrs / wk, $15 / hr, 1 or 2 semesters)
>   - Dan Maxwell is looking for a faculty partner (external to library) and project plan to pitch to the libraries to secure funding (could be lesson development)
>   - plan also needs to include mentoring plan stuff for the intern

Are we still interested in this? If so, we should get in touch with Dan and see if he's still interested. Otherwise, we can probably close this issue.

**Comment by stuckyb** [comment]
I think we can close.  I'm guessing if Dan were still interested in pursuing this he'd have reached out again, but it looks like nothing has happened since last August.

**Comment by stuckyb** [comment]
Closing, as there has been no further discussion in nearly a year and a half.  If Dan has further interest in this, we can re-open.
