### ISSUE TITLE
Waitlist management

### ISSUE THREAD

**Issue by ha0ye** [UF-Carpentry/Coordination#60]
I know we have a waitlist for workshops... is there one for instructor training?
And do we have recommendations for folks to stay informed on those opportunities other than the email list?

(I'm wondering if a public sign-up of some kind might be useful...? Or additional ways to solicit feedback from community about desired workshops)

**Comment by mjcollin** [comment]
Yes, managing this communally would be great. A public signup might lead to many people just putting their names on it and creating a second inner circle of people who know how to get access to workshops. I see waitlists as being a courtesy award for people we couldn't do anything better for, not as a way for people to indicate their future intentions.

But I do like the soliciting feedback aspect and signing up for informatics-teaching-l when all you want to know is when the next workshop is isn't a great fit.

(A side note about signups - The last couple workshops have used the printed registration pages which have people's home addresses, phones, and emails on them. I would like to be sure to use simple lists of names in the future.)

**Comment by mjcollin** [comment]
Also, we don't ask people to join a waitlist. The people who email us to ask are those to who take the initiative to think of it which of course is a biased subset of our target audience. Maybe we shouldn't have a waitlist at all.

**Comment by stuckyb** [comment]
Here is my attempt to document the plan we hatched at our last board meeting.
1. Prior to a workshop, we will identify the entities (e.g., departments, labs, etc.) that have reserved workshop seats and the number of reserved seats available to each entity.
2. _X_ days before the workshop, we will open up enrollment for the reserved seats.
3. After the reserved seat enrollment period ends, we all remaining seats will be available for open workshop enrollment.

Questions:
1. What if the number of reserved seats exceeds the number of available seats?
2. What is the value of _X_ in number 2, above?
3. How do we track reserved seat allocation throughout the year?  Shared Google doc?  Something else?

**Comment by KristinaRiemer** [comment]
WRT question 1, could we only offer a subset of the total reserved seats to each entity for any given workshop? For example, if WEC gets 6 seats throughout the year, only offer them 2 per given workshop?

**Comment by stuckyb** [comment]
That could certainly work.  The potential downside is that reserved seats might not get used efficiently.  (E.g., suppose entity A is especially interested in a particular workshop that does not interest the other entities.  In that case, it is likely that at least some reserved will go unfilled that could have been taken by additional enrollees from entity A.)

Here are two more options:
1. First come, first served enrollment for the reserved seats.  This is easy to administer, but "scramble competition" is not always a very fair way to allocate resources.
2. Use a lottery to randomly select the "winners" of reserved seats.  This is objective and fair, but it requires more administrative work.

**Comment by stuckyb** [comment]
Decisions at the board meeting:

* No more than 50% of the seats at any workshop should be reserved seats.
* _X_ days before the workshop, we will ask all entities with reserved seats to submit names of potential participants.
* If the total number of participants exceeds the number of available reserved seats for the workshop, the number of participants will be reduced as follows:
  1. Randomly select an entity _E_ from among the entities with the least number of prior selections.
  2. Randomly choose a participant from _E_ to remove from the workshop.
  3. Goto step 1 unless the number of remaining participants equals the number of available reservations.

**Comment by ha0ye** [comment]
(assigning this to myself to update the coordination wiki with this info and close this issue)
