### ISSUE TITLE
Dealing with ties when voting for board members

### ISSUE THREAD

**Issue by mjcollin** [UF-Carpentry/Coordination#61]
This semester we ended up needing to address a tie when electing the fall 2018 board. Some suggested options:

1. Hold a run-off vote. This incurs the overhead of running another election.
2. Hold a vote but limit the eligible voters to some smaller set eg current board members, instructors only, just people who voted last time, etc. This is less ideal but acknowledges the fact that we sent 400 invitations to vote and got <10% responses so we probably shouldn't bother people too much. 
3. Allow both to serve.
4. Draw lots.

**Comment by justinmillar** [comment]
I agree with @KristinaRiemer, this approach also allows us to mask the identities of the tied individuals.

**Comment by Cactusolo** [comment]
I agree with @KristinaRiemer.

Miao


Send from my ICrazy

On Sep 21, 2018 at 12:41, <Justin Millar <notifications@github.com>> wrote:

I agree with @KristinaRiemer <https://github.com/KristinaRiemer>, this
approach also allows us to mask the identities of the tied individuals.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/UF-Carpentry/Coordination/issues/61#issuecomment-423599150>,
or mute the thread

**Comment by mjcollin** [comment]
Lots it is (also received emails concurring). Leaving open to update charter when next board is installed.

**Comment by mjcollin** [comment]
Based on feedback and further discussion, the board decided to allow both tied members to be on the board. Still leaving open for the next board to address this issue formally in the charter.

**Comment by gaurav** [comment]
The board just voted on this (without a tie!) and discussed the results. We decided that the best approach would be:
- A board size of 7 members would be ideal.
- Having a board of 8 or 9 people will be fine, as there will be more people to divide our work up. Therefore, a few ties are fine and we will seat additional board members.
- Having more than nine people would make the board too large and unwieldy. In that case, it will be up to the board that is administrating the election to decide how to reduce the number of board members to nine members or fewer.
- We considered explicitly specifying a method for the board to use (random chance, run-off election) but decided to give them the discretion in the unlikely event that 7th, 8th, 9th and 10th place (or more) all receive the same number of votes.

I've made a pull request with a first draft at making this change at UF-Carpentry/website#20. Please make any changes to it there if you'd like! Updating the charter requires a 2/3 vote of the board, which might take place at our next board meeting on December 11, 2018.
