### ISSUE TITLE
Fall 2018 travel awards

### ISSUE THREAD

**Issue by mjcollin** [UF-Carpentry/Coordination#62]
Time for travel awards again. We have about $1000 to award which I think we are splitting in to either two $500 domestic awards or $1000 international. Timeline discussed at this meeting:

9/28 - Announce applications are open to eligible people
10/5 - Close applications
10/9 - Announce awards

**Comment by josephaandreoli** [comment]
Hi Matt, thank you for the examples you provided! My gmail username is josephaandreoli@gmail.com

**Comment by josephaandreoli** [comment]
Hey Matt, are there other packages I should install when running summarize_instructors.R? When I run the script, event is not found in the data. I'm using deprecated_merged_instructors.csv as the csv. 
Thanks,
Joe

**Comment by mjcollin** [comment]
Try instructors. Csv

**Comment by ha0ye** [comment]
Selection for the travel awards was completed, and the folks informed right? Was there an announcement?

**Comment by gklarenberg** [comment]
Travel awards have been awarded and blog posts are up. Closing this issue.
