### ISSUE TITLE
Location for internal documentation on operations

### ISSUE THREAD

**Issue by mjcollin** [UF-Carpentry/Coordination#63]
Quoting Hao from #52 

> My preference is to keep some of the organizing instructions off of the website - the wiki is easier to edit, and while there's nothing wrong with operating transparently, I think having some divide between inward-facing docs and outward-facing docs is useful. (same goes for e.g. board member onboarding guide)

I agree and while it is a second place to look, I worry about the overhead of editing the web site excluding people who don't want to get in to Jekyll development details. The wiki is much more accessible.

If there is consensus, I will pretty up the wiki to remove all the old pointers to things that have been migrated to the web site and also link to the wiki from the web site so people can find our documentation. I think our internal process documentation needs to be public because one of our roles is as a model to other groups who want this level of Carpentry organization.

**Comment by stuckyb** [comment]
+1

**Comment by mjcollin** [comment]
Cleaned up github wiki, add new page on digital property and stub page for #65 . Linked at the bottom of the governance page on the public web site.
