### ISSUE TITLE
UF Carpentry -> UF Carpentries

### ISSUE THREAD

**Issue by ha0ye** [UF-Carpentry/Coordination#64]
Can we rebrand the website and wherever else to use "UF Carpentries Club" instead of "UF Carpentry Club"?

I feel like the former is at least a bit more consistent with the name of the mothership organization, and *slightly* less likely to have us confused with a group of woodworking enthusiasts...

**Comment by stuckyb** [comment]
Sounds good to me.

**Comment by mjcollin** [comment]
Yeah, not sure what fit of madness made me pick "carpentry" singular but I'll go fix it. Things might be fishy some time in the next couple days but it'll be working before the workshop emails get sent out.

**Comment by ha0ye** [comment]
Well, Data Carp and Software Carp are singular...

**Comment by mjcollin** [comment]
Do we want to re-name the Github organization too? Consequences:

1) Broken workshop page links like https://uf-carpentry.github.io/2018-10-04-ufii-one-day/
2) "uf-carpentry" will become available for someone else to claim although we could try to claim it quickly
3) If we do get the old org name, we'll need to set up redirecting of traffic as best as possible.

**Comment by mjcollin** [comment]
Registered new domain, waiting 24 hrs for propagation.

**Comment by mjcollin** [comment]
Sorry this fell behind. DNS and domain are all set up. I need access to the web hosting set up to finish the change. Can someone document the web setup at https://github.com/UF-Carpentry/Coordination/wiki/Digital-Property ?

**Comment by mjcollin** [comment]
It does, does this web host have the ability to redirect the old URL to the new one? If not, I can set that up independent of the web hosting company.

**Comment by ha0ye** [comment]
I believe so. Right now www.uf-carpentry.org is an alias, but there's this info. Should I proceed with this?
![screen shot 2018-10-09 at 11 15 12 am](https://user-images.githubusercontent.com/5835366/46679262-9b02bd80-cbb4-11e8-85d1-65034d341595.png)

**Comment by mjcollin** [comment]
Sure, give it a try. I suggest changing the 301 (permanent) to a 302 (temporary) redirect until we're sure we like the behavior.

**Comment by mjcollin** [comment]
Last call for any noticed bugs. @ha0ye you're good to change the 302 to a 301.
