### ISSUE TITLE
wiki/repository organization

### ISSUE THREAD

**Issue by stuckyb** [UF-Carpentry/Coordination#68]
So far, documentation about the board and board positions has gone in the wiki for this repository.  As we begin to accumulate more of this documentation, does it still make sense to put it in the "coordination" repository?  I suggest that we either create separate repositories for workshop management and board operations, or we rename this one to something more inclusive.

**Comment by gaurav** [comment]
I like the idea of a single repository with both club information and workshop management information, but I agree that "Coordination" might not be the best name for it. We could call it "Organization" or "Club" maybe?

**Comment by ha0ye** [comment]
I prefer a combined repo, but I think it would be helpful to reorganize the pages under the categories of "workshop organization" and "board duties".

What about "Club Activities" as a combined name?

**Comment by mjcollin** [comment]
There exist some links to https://github.com/UF-Carpentry/Coordination/wiki out in the wild, such as the blog post we wrote about a year ago. If you want to rename the existing repo, make a new repo with the old name and make a wiki page with links to the new places.

**Comment by ha0ye** [comment]
I did a bit of cleaning of the wiki pages - here's one way, going forward:
* keep the wiki name the same (as it might break too many things, and "coordination" sounds general enough.
* keep the divide among wiki pages between board operations and workshop operations, but rename some of the pages for better organizing
* make a note of missing wiki pages to add if appropriate.

**Comment by ha0ye** [comment]
I think this is in a good place for now, and we should keep doing individual issues for further tasks.
