### ISSUE TITLE
Comment on Carpentries member organization report

### ISSUE THREAD

**Issue by mjcollin** [UF-Carpentry/Coordination#69]
From Elizabeth:

As part of our commitment to strengthening our communication with and support of Member Organisations, we are excited to send you this preview of our Member Organisation report. What is shown on this preview is only a portion of the individualized data and feedback that we are working to make available to member organisations, to empower you to continue to strengthen and grow the Carpentries activities at your organisation.

We would greatly appreciate your feedback on this report at the Member Organisation Council meetings next week. If you have not already, you can view and sign up for the various times and dates of the meetings on the meeting etherpad. These meetings are a chance to discuss topics like these, as well as to meet people from other Member Organisations and share ideas and approaches.

In addition to the information shown on this report, we envision that the full reports will include information about instructor training and survey responses from learners who took workshops with your organisation, as shown in the Member Organisation Report plan document. We are in the process of updating our back-end data structure in order to be able to generate these reports, so now is a great time for suggestions of additional information you would like to see! Some of information may be possible for us to include, other information not, but these reports are for you and your feedback is key to their development.

If you do not see data displayed in your report for workshops you know have taken place, you can report these workshops to our Workshop Administration team (team@carpentries.org), and this information will add to the accuracy of future reports for your organisation.

If you would like to be running more workshops than you see in your report, please feel free to reach out to us (memberships@carpentries.org) for support making the most of your membership to build community and a culture of learning at your organisation. 

Hoping to see you later this week!

Best,
Elizabeth

**Comment by gklarenberg** [comment]
@mjcollin How can we access these reports? I don't think we've addressed this at a board meeting yet, but we can table it today or at the next meeting.

**Comment by mjcollin** [comment]
It looks like I had decided not to make it public so I didn't link it here. I imported it into Google docs and it is accessible to those who have access to our folder. Please let me know if you want your Google account added:

https://docs.google.com/document/d/1rLmBKqkR2oYA8uyzo0osWrHV7N0n8wAk-D9wmpABFqk/edit

**Comment by gklarenberg** [comment]
@mjcollin I sent a request for access

**Comment by gaurav** [comment]
I think we should make this report public on our website. Is there a good reason not to?

**Comment by stuckyb** [comment]
I can't think of a good reason not to, but I agree -- let's discuss at the next board meeting.

**Comment by stuckyb** [comment]
We discussed this at the August 6 board meeting, and all present agreed that it would be fine to make the report public.  @gaurav , did you have any thoughts about where this might go on the website?  Perhaps a link to a downloadable PDF version?

**Comment by gaurav** [comment]
I've written a [short, backdated blog post](https://www.uf-carpentries.org/posts/2018-09-30-carpentries-member-site-report/) to link to the report on Google Docs. Do reopen this issue if you think we should deposit this on Zenodo or elsewhere!
