### ISSUE TITLE
Additional advertisement/engagement venues

### ISSUE THREAD

**Issue by mjcollin** [UF-Carpentry/Coordination#7]
Our last workshop did not fill so the UFII mailing list may be saturated. New places to advertise:

1. UF all graduate list - we can support this level of attention now
1. UF student groups (DSI, WEC, AIS, ISOM, etc - will reach more undergraduates)

**Comment by gklarenberg** [comment]
What about post-doc mailing lists? If they exist?

**Comment by ha0ye** [comment]
@gklarenberg We should be able to get something in the weekly postdoc email:
http://postdoc.aa.ufl.edu/newsletter/submission-guidelines/

**Comment by mjcollin** [comment]
The 3/20/18 workshop did fill and I've got a wait list of 5-6 people. This workshop was not advertised at all on the UFII mailing list; Plato did a lot of advertising and it was put on the UF gradstudent-l mailing list:

https://lists.ufl.edu/cgi-bin/wa?A2=ind18&L=GRADSTUDENT-L&D=1&T=0&O=D&X=14B05068D6EC300844

I think this means we have an advertising problem, not a demand problem.

**Comment by mjcollin** [comment]
From Valrie I. Minson vdavis@ufl.edu at Marston Science lab re social media promotion of our events:

"We’d be happy to coordinate and assist any way we can.  As a first good step, and forgive me if this is already happening, it would be good if you created Data Carpentry events via Facebook or Twitter then MSL would be happy to link to them.  In addition, here is an example of sharing skills that we would also happily retweet. I looked up Python in Twitter to see if I could find a good example and found a funny Alice Cooper video related to wrestling with pythons that would certainly attract attention."

**Comment by mjcollin** [comment]
For the 8/2018 workshops and Rezbaz, we did not get an email out to the grad list in time and as a result the workshops and baz took a while to fill. This demonstrated (see 8/14/2018 board notes) that the grad list is a key venue, or at least the UFII list is not sufficient.

**Comment by KristinaRiemer** [comment]
Was email sent out to the informatics teaching listserv?

**Comment by mjcollin** [comment]
I tried to sent the 10/4/2018 workshop announcement to the grad list through emailing Greg directly. He did not respond to two queries. I talked with Alethea about getting access to the list and she said this happens. I propose letting Alethea and Flora contact Greg in the future so potentially he can prioritize our announcements consistently rather than having to learn who is managing each workshop and whether their message is legit.

**Comment by ha0ye** [comment]
*ponders some convoluted API that routes mail through Flora and Alethea to get messages to the grad list*

**Comment by gaurav** [comment]
Should we consider setting up a Facebook page for UF Carpentries? I could take a stab at that if that would be useful.

**Comment by gklarenberg** [comment]
I guess we could. I have been informed by my kids that "all old people use Facebook" and I guess all grad students and definitely post-docs fall in that category lol. Right @josephaandreoli ?

**Comment by josephaandreoli** [comment]
As the youth consultant for the Carpentries board, I agree with @gklarenberg's kids. We should definitely do more engagement with our Twitter account (following a set of guidelines), though!
