### ISSUE TITLE
New communications role

### ISSUE THREAD

**Issue by KristinaRiemer** [UF-Carpentry/Coordination#70]
The idea behind this role is to have one point person for disseminating information about our events, including workshops and board meetings. This position will likely be for the entire duration of the board. 

List of duties: 
* Run Twitter account
* Send out emails to informatics list
* Send out emails to grad student list (via Greg)
* Update events on club website

Feel free to provide any feedback on this!

**Comment by mjcollin** [comment]
+1
This role is often neglected and one of our most common complaints is that new people to UF don't know all the things that are going on. This role could also take responsibility for making/finding some kind of clearinghouse for all the events that happen for teaching people data skills at UF.

Specifically about the grad list, see comments to #7
