### ISSUE TITLE
Spring 2019 Instructor training

### ISSUE THREAD

**Issue by gklarenberg** [UF-Carpentry/Coordination#73]
Probably somewhere March-April, same as last year - but is dependent on trainer's availability.

**Comment by gklarenberg** [comment]
I ran into @fmichonneau on Wednesday, and he said he's around until January. So he won't be here around the time we want to do instructor training.

**Comment by fmichonneau** [comment]
there is a chance I'll be around Feb 18-March 2 and/or April 15-April 26. I'll know more around Dec 20th.

**Comment by stuckyb** [comment]
Great, thanks @KristinaRiemer .

**Comment by gklarenberg** [comment]
Re-assigned to Elise, Gaurav and myself :) Correct?

**Comment by gaurav** [comment]
I think that was @stuckyb, not me. I'll double-check this at the board meeting in a bit!

**Comment by gklarenberg** [comment]
Yeah, you're right

**Comment by gaurav** [comment]
Just wanted to note that our Google Drive has two students who were waitlisted from our last instructor training at https://docs.google.com/document/d/1zwqdAhN3nPZdnnqJpBYQooBGxytQInOTo4JkmLq0xOM/edit (you need access to the Google Drive to access that file).

**Comment by gklarenberg** [comment]
> Just wanted to note that our Google Drive has two students who were waitlisted from our last instructor training at https://docs.google.com/document/d/1zwqdAhN3nPZdnnqJpBYQooBGxytQInOTo4JkmLq0xOM/edit (you need access to the Google Drive to access that file).

@stuckyb and @elisemorrison we need to follow up on this. In addition, @fmichonneau: are you all onboard with instructor training on 8-9 April? If you're coming from out of town (not sure?) we can reimburse you...

**Comment by fmichonneau** [comment]
Yes, I'm all onboard. I don't expect any needs for reimbursement. We started the website for the event at: http://fmichonneau.github.io/2019-04-08-ttt-UF/
