### ISSUE TITLE
Spring 2019 Carpentries workshop

### ISSUE THREAD

**Issue by gklarenberg** [UF-Carpentry/Coordination#74]
Need to decide what topic(s). Suggestion at 11/27 board meeting was maybe to do Software Carpentry with R (i.e. command line, git and R). We need to go over this curriculum to see if it works for us. 
Programming with R (http://swcarpentry.github.io/r-novice-inflammation/) has things in there I haven't worked with much - knitr, call stack. I kinda like the part they have in there on running R from the command line (which you need to do if you use the HPC).
R for Reproducible Science Analysis (http://swcarpentry.github.io/r-novice-gapminder/) looks a lot like the Ecology curriculum, just ordered differently. I haven't looked at the actual content but I wonder why ggplot comes before dplyr and tidyr....

**Comment by gklarenberg** [comment]
Not sure if we still need this issue as most of the discussion is currently taking place on Slack?

**Comment by ha0ye** [comment]
We're mostly set other than actually having the workshop, so I'm going to close this.
