### ISSUE TITLE
December 11 Board Meeting Agenda

### ISSUE THREAD

**Issue by ha0ye** [UF-Carpentry/Coordination#76]
* introductions
* approve last week's minutes
* vote on charter amendment to handle election ties
* status of website updates
* status of slack creation
* status of instructor training
* status of next semester workshops
  - fix date for February workshop
* status of off-site workshops program
* selection of new secretary
* other issues on coordination github
  - repo organization
  - waitlist management and sponsoring departments

**Comment by ha0ye** [comment]
Yes! I think we should discuss and turn some of those into action items.

**Comment by stuckyb** [comment]
Also, I realize that "status of next semester workshops" is already on the agenda, but choosing the date for the February workshop is one concrete task we should complete at next week's meeting.  I don't know if we want to be explicit and add that to the agenda.

**Comment by gaurav** [comment]
Here's a link to the proposed change to the charter that we're going to vote on: https://github.com/UF-Carpentry/website/pull/20

**Comment by KristinaRiemer** [comment]
This meeting was yesterday.
