### ISSUE TITLE
Change ownership of digital resources

### ISSUE THREAD

**Issue by mjcollin** [UF-Carpentry/Coordination#77]
Make the ownership of various digital resources more general and make sure appropriate people are owners:

https://github.com/UF-Carpentry/Coordination/wiki/Digital-Property

**Comment by ha0ye** [comment]
@mjcollin Can I get access to the google drive folder? I'd like to send out the email to request instructor signups for the Feb. 11-12 workshop - and it sounds like that info is in that folder. My weecology email is fine for access.

**Comment by ha0ye** [comment]
-[ ] give Board members access to the ufcarpentries@gmail.com email account
-[ ] transfer ownership of the Google Docs folder (SwC_DC_UF) to the gmail
-[ ] create policies for access, e.g. giving more folks access to the photos folder might be fine, but participants and budget should be private

**Comment by mjcollin** [comment]
I did one thing tonight: I have changed the sharing to add additional owners to the Google Drive folder. It seems only @gmail.com people can be owners since that was the original domain that I made it under and @weecology.org and @badmatt.com Google Apps domains can't be owners. Any owner can manage owners and sharing. Geraldine, Gaurav, Elise, and Brian are owners.

**Comment by gaurav** [comment]
I think we decided at today's board meeting to have `ufcarpentries@gmail.com` forward to everybody on the current board. @mjcollin Could you please give me access to that account so I can set that up?

Alternatively, we can apparently use Google Groups to create a shared e-mail account: https://support.google.com/a/answer/167430?hl=en

**Comment by mjcollin** [comment]
A added the board to the fowarding list for ufcarpentries@gmail.com. I think only one person has ever sent email to this address though and I forwarded it to everyone.

There is a long password for this account that I'm happy to share with someone. I'll be up at the UFII around 5:00 this Wednesday.

**Comment by ha0ye** [comment]
Thanks, I can meet you on Wednesday, @mjcollin.

**Comment by ha0ye** [comment]
@mjcollin, I think I missed you yesterday... when are you next going to be around to transfer accounts?

**Comment by gaurav** [comment]
@ha0ye I got the password yesterday, and can pass it on to you whenever you like!

**Comment by ha0ye** [comment]
@gaurav Can you send it over via keybase? https://keybase.io/hao_and_y
