### ISSUE TITLE
Carpentries "Champions"

### ISSUE THREAD

**Issue by fmichonneau** [UF-Carpentry/Coordination#8]
The Carpentries have started a "Champions" group for people who are interested in the creation and support of Carpentries communities.

It seems that the UF Carpentry Club could provide some insights into how to do that at a local scale and learn from other group experiences. 

There was a Champions meeting yesterday, the notes of the meeting are available http://pad.software-carpentry.org/champions

There is also a Slack channel (#champions) on the SWC slack. If you are not there already you can join here: https://swc-slack-invite.herokuapp.com/

There is a mailing list that is used primarily to announce future meetings: https://groups.google.com/a/carpentries.org/forum/#!forum/champions-announce

**Comment by mjcollin** [comment]
I've been to a couple calls and invited others. I dropped the links to the notes, slack, and list on the front page of our wiki for lack of a better place, especially since we're in the middle of moving to a new site. Closing as there seems to be no action to take.
