### ISSUE TITLE
Agenda items for Board Meeting on Feb 19, 2019

### ISSUE THREAD

**Issue by ha0ye** [UF-Carpentry/Coordination#84]
* approve the [previous minutes](https://github.com/UF-Carpentry/website/blob/master/_minutes/Board-2019-02-05.md)
* updates from Hao's meeting with Alethea
  - viewing access to UFII / UFBI calendars
  - increase in catering fees
  - DOCE (conference registration system) can support free and discounted rates (need names and emails to check eligibility)
  - DOCE does not support waitlist - Alethea/Flora/we manage that ourselves
  - use Alethea/Flora to help keep track of commitments to financial sponsors (cc them on emails)
* **STICKERS** for future workshops 🦄 
* update LICENSE docs for website
* invite Taylor Paisie / Carla Mavian to discuss planning for April 11-12 EPI workshop? (cc @gklarenberg)

**Comment by elisemorrison** [comment]
Additional items to include for the agenda:
Update from Feb 11/12 workshop
Workshop wait list/early registration
Board approve/discuss scoring criteria for instructor training applications
Board approve budget to present to IFAS

**Comment by josephaandreoli** [comment]
Instructor training incentive for funding organizations

**Comment by ha0ye** [comment]
> Workshop wait list/early registration

🙀

**Comment by ha0ye** [comment]
Workshop sign-in sheets:
* What do Flora and Alethea need re: possible auditing for food expenses?
* Can we redact addresses and phone numbers?
* Does the registration form accept chosen names? Can we use that for sign-ins?

**Comment by elisemorrison** [comment]
https://hackmd.io/QguYHua6RR6lzftluo9YPQ#
