### ISSUE TITLE
Archive feedback from 2019-02-11-ufii workshop

### ISSUE THREAD

**Issue by ha0ye** [UF-Carpentry/Coordination#85]
@josephaandreoli and @stuckyb - can you be sure to update our docs with the sticky note feedback from this week's workshop?

Path to the document inside the shared google folder:
"SwC_DC_UF/workshop info/2019-02-11-ufii/Feedback"

**Comment by josephaandreoli** [comment]
Hey @ha0ye , I left those post-its with you after concluding my lesson because I didn't know if you had seen them yet.

**Comment by ha0ye** [comment]
Cool. I was wondering if that might be the case, since they seemed a little mixed up when I got around to digitizing them.

**Comment by stuckyb** [comment]
I just added the notes from the shell lesson.

**Comment by ha0ye** [comment]
Thanks, all.
