### ISSUE TITLE
[proposal] waitlist / priority registration management

### ISSUE THREAD

**Issue by ha0ye** [UF-Carpentry/Coordination#86]
context:
* we have incentives for funding organizations in the form of priority registration for regular workshop seats, and for instructor training
* Flora and Alethea are able to help us with various aspects of managing registration and communicating with the groups that are funding us

proposed changes (immediate):
* set up google sheet and google form under the ufcarpentries@gmail.com account
* give departments codes (individualized for each department x workshop - this allows us to verify number of seats remaining for a department and that the participants are signing up for the correct workshop) that they can distribute to folks for advance registration
* give Flora and Alethea access to the google sheet where the form responses are collected
* set clear and advance cut-off dates for usage of those seats

proposed changes (long-term):
* budget in reservation of seats for funding organizations (i.e. change priority registration into seat reservation)
* develop long-term schedule of workshops (how many workshops in fall, spring, summer? what content? let funding orgs. decide how many seats they want to reserve for those specific workshops)

Notes:
* get rid of random selection (though continue to offer that as an option for departments if they so choose - it just seems to be less desirable for them)
* using a google form enables us to confirm registration (since the reserved seats will be added automatically), and it will eliminate one extra hoop of communication - departments can distribute the info directly

**Comment by stuckyb** [comment]
Thanks, @ha0ye , for putting this together (and for the reminder to review it!).  Good ideas here, a think.  A few questions/comments:
  * Under long-term changes, can you clarify what you mean by "seat reservation"?  Does that mean that they get _x_ number of workshop spots for free?
  * If we have people sign up using the google form, would they then later register using the standard UF system (to handle payments, e.g.)?  If so, could we add a "priority registration code" field directly to the UF registration form and eliminate an extra step?

**Comment by ha0ye** [comment]
Yup, I think free seats is easier to market as a benefit of sponsorship. (Though we would need to check our budgeting to see what is feasible).

Signing up through the google form bypasses the UF registration system - Alethea and Flora can use the google sheet of responses to add those folks manually.

**Comment by ha0ye** [comment]
per [March 12 board meeting](https://www.uf-carpentries.org/minutes/board-2019-03-12/), @ha0ye is going to start setting this up. Given the timeframe, with the EPI workshop coming up in a month, this will likely not be implemented until the workshop after that. (and give us time to work out various kinks with the google docs, etc.)

**Comment by gaurav** [comment]
As of right now, we seem to have a consensus that we should open half the seats early and send our sponsoring groups an e-mail letting them register then. This issue now covers writing this out as a document or on our website so that the board can vote on them.
