### ISSUE TITLE
Spring 2019 Instructor Training Application

### ISSUE THREAD

**Issue by elisemorrison** [UF-Carpentry/Coordination#87]
I came up with a plan for the training application. If everyone could give their input by Monday 2/25, we could get the application/announcement sent out early/mid next week.

The Carpentries application will be used: https://amy.software-carpentry.org/forms/request_training/ An announcement will be sent out at least a month before the Instructor Training, some suggested language in included below.
	
> The University of Florida Carpentries Club will be hosting a two-day Carpentries Instructor Training on [dates] at [location]. This class is offered to anyone who is interested in becoming a Carpentries instructor, and those who complete the two full days and some short follow-up exercises online will be certified to teach Software Carpentry, Data Carpentry, and Library Carpentry workshops. Please fill in the online application form if you wish to take part in this course and include the code [workshop code]. When you apply, please include a description of how you plan to use the tools/skills gained from the workshop in the “anything else?” text box at the bottom of the application.

Rubric: 
Three board members should serve as judges. Judges will assign a score to each application, and will meet to compare scores and get a final list of attendees.

The questions from the Carpentries application will be scored as follows: 

Affiliation (maximum 3 points):
1 point – well represented department
2 points – moderately represented department
3 points – underrepresented department

In which of the following ways have you been involved with The Carpentries (max. 6 points): 
Lists ways that they have been involved with Carpentries (helper, learner, instructor, etc.) 
+ 1 point for each way that they have been involved with The Carpentries

How often would you expect to teach Carpentry Workshops after this training? (max. 3 points): 
Not at all: 0 points
Once a year: 2 points
Several times a year: 3 points
Other: Depends on what is input; points at the discretion of judges, if high value, at least 2 points should be assigned

Why do you want to attend this training? (max. 3 points): 
If applicant seems marginally interested, only wants to attend to improve CV: 0 points
If applicant seems interested, but doesn’t seem to know why they are taking the training: 1 point
If applicant seems moderately motivated: 2 points
If applicant seems highly motivated, enthusiastic: 3 points 

How do you expect to use the tools/skills learned in this training? (max. 3 points)
If applicant does not have a clear idea of how they will use these skills/tools: 0 points
If an applicant has a vague idea of how they will use these skills/tools: 1 point
If an applicant has a moderate plan for how they will use these skills/tools: 2 points
If an applicant has a clear plan for how they will use these skills/tools: 3 points

**Comment by ha0ye** [comment]
re: affiliation
* Is there modified scoring for non-UF, or non-Gainesville affiliations?

re: past involvement with Carpentry Workshops
* Does previous attendance at a workshop count for past involvement?
* What about involvement with a similar group that isn't Carpentries-related, e.g. R-Gators, DSI, etc?

**Comment by elisemorrison** [comment]
re: affilication
* I think we could include non-UF, non-Gainesville in the "underrepresented category." Alternatively could add a new point for that

re: past involvement
 * Yes; the question on the application has six categories: Helper, Instructor, Workshop host, Learner, Workshop organizer, Contributed to lesson materials 
* The application doesn't have any nuance wrt listing involvement in similar group, the closest question is "I have been an active contributor to other volunteer or non-profit groups with significant teaching or training components. " with a text box that allows them to list organizations. We can add extra points for this.

**Comment by ha0ye** [comment]
Ah, gotcha. I hadn't looked at the form in a while. Thanks for clarity on the rubric.

**Comment by stuckyb** [comment]
Great work on this, Elise.  Thank you!!  Using the "anything else" box to answer a custom question is  a great idea.

I think the suggested scoring rubrics all look good, except I do have one comment on scoring the "previous participation" category.  If someone has been involved in a single teaching-related category more than once (e.g., teacher at 2 workshops), they get less credit than if they had served once in multiple categories (e.g., attendee at 1 workshop and helper at 1 workshop).  Perhaps we could simplify the scoring to something that gives more weight to teaching-related roles while keeping the maximum total relatively low, e.g.?:
  * previous Carpentries involvement as a workshop participant: 1 point
  * previous Carpentries involvement that includes teaching or other teaching-related roles (helper, workshop organizer, curriculum development): 2 points

**Comment by stuckyb** [comment]
Great work on this, Elise.  Thank you!!  Using the "anything else" box to answer a custom question is  a great idea.

I think the suggested scoring rubrics all look good, except I do have one comment on scoring the "previous participation" category.  If someone has been involved in a single teaching-related category more than once (e.g., teacher at 2 workshops), they get less credit than if they had served once in multiple categories (e.g., attendee at 1 workshop and helper at 1 workshop).  Perhaps we could simplify the scoring to something that gives more weight to teaching-related roles while keeping the maximum total relatively low? E.g.:
  * previous Carpentries involvement as a workshop participant: 1 point
  * previous Carpentries involvement that includes teaching or other teaching-related roles (helper, workshop organizer, curriculum development): 2 points

**Comment by elisemorrison** [comment]
Hi Brian, 
I'd be happy to incorporate that change into the rubric. Does anyone else have any comments/edits for the rubric?
Thanks!

**Comment by ha0ye** [comment]
What about past experience teaching, but not in a Carpentries context? Would that also substitute for the 2 points for involvement with Carpentries teaching or curriculum development?

Does signing up for the instructor training waitlist automatically put someone at 2-3 points for motivation? (I think that info might come automatically with the results from the request form.)

**Comment by elisemorrison** [comment]
In the application, the "past experience teaching" question is separate from the "previous involvement in carpentries" question. To keep the rubric as clear and reusable as possible, I think it would be best to keep the scoring specific to each question - without trying to merge questions/categories. 

I think points for "previous involvement with the carpentries" should be scored separately from the "previous teaching experience" question on the application. I'd be happy to add an additional point scoring for the "previous teaching experience" question, if needed.

In the same way, I think it would be good to add an additional +2 points if a person is on the waitlist, but I think we should avoid lumping it in with the score from the "why do you want to attend this workshop" motivation question.

What do you all think?

**Comment by ha0ye** [comment]
I think my motivation for wanting to lump things together is to not privilege folks who have had more past experience with Carpentries vs. those who might be using instructor training as the path to getting more involved. Realistically, I'm not sure if there are many people in that category, or what the scoring process will even favor in the end...

My thinking about past teaching experience, for example, is that an applicant should get credit for having some, regardless of whether it is Carpentries-related or not. But if the points are assigned across two categories, then an applicant could receive twice the points for having participated in both, which could outweigh other considerations, such as motivation and willingness to teach in future workshops.

I like scoring application questions individually - that makes evaluating the applications much easier. I guess one could merge the results from multiple questions together by assigning a maximum cap to the sum of multiple components?

Anyway, maybe I should stop commenting for now and leave things to the actual instructor training subcommittee (working group? task force?).

**Comment by elisemorrison** [comment]
I think you bring up some good points, and I completely agree that we don't want to privilege people who have worked with Carpentries more vs. those who want to get more involved. But, I do think we should try to keep the rubric as simple and as close to the application questions as possible, since we want to make sure that the next round of judges can follow the rubric without recreating the wheel again.

What if we keep the "carpentries participation" points low (max. 3 points, if they both participated and taught in workshops) as suggested by Brian, and include some points for previous teaching experience, such as +1 point if they have "I have been an active contributor to other volunteer or non-profit groups with significant teaching or training components," and up to +2 points based on the "Description of your previous training in teaching."  That way people who have taught in non-carpentries related situations can still get points.

**Comment by gaurav** [comment]
This looks great -- thanks so much, Elise!

**Comment by stuckyb** [comment]
That sounds like a good plan to me, Elise.  Also, I like the idea of 2 extra points for folks on the wait list.  I think we're good to go here.

**Comment by gklarenberg** [comment]
Yep, all sounds good to me as well! Elise - do you have a document/Excel sheet with the rubric and scoring summarized?

**Comment by gklarenberg** [comment]
Btw - officially our membership says we can train 15 people? See https://carpentries.org/membership/ Is this really a thing? Since I think in all the previous instructor trainings we trained more people

**Comment by ha0ye** [comment]
> Btw - officially our membership says we can train 15 people? See https://carpentries.org/membership/ Is this really a thing? Since I think in all the previous instructor trainings we trained more people

My guess is that the 15 refers to being trained online (as with the Silver-level membership), but that the capacity for in-person training depends on space and # of instructor trainers that can be present.

**Comment by elisemorrison** [comment]
> 
> 
> Yep, all sounds good to me as well! Elise - do you have a document/Excel sheet with the rubric and scoring summarized (with the changes)?

I have a word document at the moment - how would you like me to share it with you?

**Comment by elisemorrison** [comment]
Here's the word doc; it includes the workshop code for this April's workshop. What application deadline do we want to set?  
[2019_02_26_Instructor_Training_App_Rubric.docx](https://github.com/UF-Carpentry/Coordination/files/2910559/2019_02_26_Instructor_Training_App_Rubric.docx)

**Comment by ha0ye** [comment]
Oooh, and since next week is spring break, we should probably send out the heads up about instructor training for our financial sponsors now.

**Comment by elisemorrison** [comment]
Yeah, I think it would be good to send it out. What application deadline do we want to set?

**Comment by ha0ye** [comment]
If next week's board meeting is going to be pushed back (spring break), my suggestion would be March 25 (2 weeks prior), so that you all can do a quick update for the meeting on Tuesday the 26th and then notify the selected applicants to register during the week of April 1.

**Comment by elisemorrison** [comment]
Ok, that sounds good. Also, do board meetings usually get pushed back for spring break?

**Comment by ha0ye** [comment]
I think many members of the board won't have conflicts, but it might be good to avoid meetings during official holidays to ensure that the meetings remain open and accessible to the broader UF community.

Ultimately, it's up to the current chair... 😉

**Comment by stuckyb** [comment]
An application deadline of March 25 sounds good to me.  Elise, I am happy to help draft the letter to the sponsors, but I don't have capacity to work on that today.  Tomorrow should be better, in theory.

**Comment by elisemorrison** [comment]
Ok, I think it would be best then to postpone for spring break - I'll send out an email to the rest of the board

**Comment by elisemorrison** [comment]
> 
> 
> An application deadline of March 25 sounds good to me. Elise, I am happy to help draft the letter to the sponsors, but I don't have capacity to work on that today. Tomorrow should be better, in theory.

Hey Brian, If you wouldn't mind sending out the letter to the sponsors when you have time tomorrow, that would be great! Just let me know if you need any help

**Comment by stuckyb** [comment]
Sure!  Three questions:
  1. @ha0ye , since you contacted sponsors about the last workshop, do you (or we) have a list of preferred email address contacts for each sponsor?  (Should be transmitted privately, I suppose.)
  2. I don't want to make any mistakes in how we describe what we can offer, so to be clear: we are offering sponsors early registration and reserved seats for the instructor training, but they still have to pay regular workshop price, correct?  1 reserved seat per $1,500 of funding, right?
  3. Is the cost of the instructor training $45, or something different?

**Comment by gklarenberg** [comment]
Let’s not call it reserved seats, I think that created the confusion last time. "Priority registration” perhaps?

On Feb 28, 2019, at 1:49 PM, stuckyb <notifications@github.com<mailto:notifications@github.com>> wrote:


Sure! Three questions:

  1.  @ha0ye<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ha0ye&d=DwMFaQ&c=sJ6xIWYx-zLMB3EPkvcnVg&r=rOAxZ7C1XBj4sC0urSW_NMzKkQ6L3H4gaBwYk1Gr3WA&m=Ty4QiHxInDYo2fyUAnUHYvxGAD-C_oMvPvn3sA_xpqo&s=pOR90QwcZi7AoMMcqzJv0y-C9woxhdbLzScsVcRth38&e=> , since you contacted sponsors about the last workshop, do you (or we) have a list of preferred email address contacts for each sponsor? (Should be transmitted privately, I suppose.)
  2.  I don't want to make any mistakes in how we describe what we can offer, so to be clear: we are offering sponsors early registration and reserved seats for the instructor training, but they still have to pay regular workshop price, correct? 1 reserved seat per $1,500 of funding, right?
  3.  Is the cost of the instructor training $45, or something different?

**Comment by stuckyb** [comment]
Oh, right -- good point!

**Comment by stuckyb** [comment]
Oops, I meant $46, not $45.

**Comment by stuckyb** [comment]
Okay, but wait a minute -- instructor training signup is not first come, first served like an ordinary workshop.  We are evaluating everyone based on their applications.  So, remind me why we need to notify sponsors before everyone else?

And even if we don't call them "reserved seats", sponsors do get that benefit, right?

I know we've discussed some/all of this before, so I apologize for my forgetfulness.

**Comment by ha0ye** [comment]
My thinking was that sponsors would get to designate 1 person to auto-pass through the evaluation process (they still have to fill out the application form in order for Carpentries to keep records of instructors, though).

From the last board meeting or two, though, it sounded like we just guarantee that at least 1 person from the sponsoring org gets to attend instructor training.

**Comment by stuckyb** [comment]
Okay, that's also what I was thinking.  So maybe the procedure here is to send out the mass email asking for applications, and at the same time, send a second message to the sponsors reminding them that they get a guaranteed seat and ask that they encourage people from their group to apply.

**Comment by ha0ye** [comment]
I *personally* like the freebie option (i.e. bypassing our evaluation system), as it allows sponsors to ensure that someone from their department/organization can get pedagogy training even if that person doesn't necessarily align with the club's objectives to sustain a pool of instructors for the future.

It seems like a reasonable hedge against the possibility that we (the board) might be thinking too narrowly about the pedagogy needs, and gives some of the responsibility and decision-making to our sponsors to identify folks who can benefit from instructor-training. (It also trusts that they can make responsible decisions, but 1 seat out of 24 is not a big cost, IMO.)

**Comment by stuckyb** [comment]
I agree, but I think we could implement that option via the application system.  E.g., ask everyone to apply the usual way, evaluate and rank all of the applications, then flag applications from sponsor organizations and bump up any, if needed, to meet the reserved seat quotas.  If there are multiple applications from a sponsor, and not all made the cut, we could ask our sponsor to help break the tie.

I wonder if just doing everything through the online app might be simpler than trying to coordinate multiple registration streams.

**Comment by ha0ye** [comment]
On the flip side, we don't have an online app for "regular" workshops, so using the same priority registration system across all our workshops can be more consistent for our sponsors.

**Comment by stuckyb** [comment]
Yes, but I think it is also simpler for sponsors to just send an email to their departments with an application URL than it is for them to try to solicit nominations, gather responses, decide on a "winner", and then communicate that back to us.  I don't feel *that* strongly about it, though, and if consensus is for requesting nominations, I'd be fine with that. @elisemorrison or @gklarenberg , do either of you have thoughts about this?

**Comment by gklarenberg** [comment]
Okay. Sorry for coming to this discussion late, but from what I understand, the option are:
1) Get departments to tell us the name of the person they want to send (nominate), still have these people fill in the online form, but more for admin/stats purposes. These people get a spot.
2) Have everyone go through the app system, flag apps from sponsoring departments, and pick at least one of those apps.
I'm kinda in favor of #1. I think it's more transparent for sponsoring departments that they actually get the spot. However, I can see how it could be a burden to the department to pick one person and tell other people to just apply online and see if they get in. Like, that kinda sucks (don't judge, I have teenager at home). So, maybe an option #3, ask them if they want to nominate a person or if they want people to apply online and we make sure we pick at least one...? Too convoluted?

**Comment by stuckyb** [comment]
I had imagined that when we sent the email to the sponsors, we'd include:
  1. A reminder that they had (at least) one guaranteed spot.
  2. The application URL, with encouragement that they circulate within their department and ask people to apply.
  3. A statement that if not all applicants from their department made the initial cut, we'd contact them to discuss whether they'd like any input on who gets selected.

That way, neither we nor the sponsoring departments have to go through the hassle of soliciting nominations and choosing a "winner" unless it is actually necessary.  I *think* that is basically your option 3, Geraldine.

**Comment by stuckyb** [comment]
Just so we don't lose track of this, does anyone else want to weigh in here?  @elisemorrison , do you have any thoughts about the best way to handle "reserved seats" for the instructor training?

**Comment by elisemorrison** [comment]
Thanks for the input - sorry I've been out sick for a few days. I think that Geraldine's option 3/what @stuckyb described above sounds like a good option.

**Comment by gklarenberg** [comment]
@stuckyb I agree with your proposal

**Comment by elisemorrison** [comment]
Great! Who would like to send out the announcement to sponsors? Also, considering the timeline, we should also probably send out the general announcement for the workshop soon, so people have time to fill out the application, and we have time to judge them.

**Comment by elisemorrison** [comment]
Great! Who would like to send out the announcement to sponsors? Also, considering the timeline, we should also probably send out the general announcement for the workshop soon, so people have time to fill out the application, and we have time to judge them.

**Comment by stuckyb** [comment]
Are we ready to send out both emails?  I have sponsor contact info from Hao, so I'd be happy to send the sponsors email, at least.  Here's an attempt at a draft of an email to sponsors, with inspiration from emails Hao and Kristina sent about previous workshops/trainings:

> Hello,
>
> On behalf of the board of the UF Carpentries Club, I want to thank you for your financial support of our mission to provide affordable and accessible informatics training for the UF community in an inclusive learning environment.
>
> On April 8 and 9, we will be hosting a Carpentries instructor training workshop here at the University of Florida (you might have noticed a recent email announcement about this workshop).  The purpose of this workshop is to train instructors to use effective, evidence-based instructional practices while teaching Data and Software Carpentry workshops.  After the workshop, participants will have the opportunity to complete Carpentries instructor certification and become eligible to teach two-day Carpentries workshops.
>
> Because of limited space, we ask anyone who would like to participate in the workshop to complete a short application; after the application deadline, we use a set of merit-based criteria (LINK HERE) to evaluate all applications and choose which applicants to invite.  However, because _____________ is a financial sponsor of UF Carpentries, ____________ has a reserved seat for ___ participant in the workshop.  You do not need to do anything in particular to use this/these reserved seat(s).  We ask that you simply encourage people in your department to apply for the workshop.  We will evaluate their applications using the same criteria mentioned above, but we will guarantee that at least one person from your department gets a seat at the workshop.  In the case that not everyone from your department who applies makes the initial cut, we will contact you to see if you would like to have input on who receives invitations to participate.
> 
> For reference, here is a summary of the application instructions from the workshop announcement email: To apply for the instructor training workshop, please fill out the form at https://amy.software-carpentry.org/forms/request_training/.  Use the code "florida-april2019" in the "Group name" box to specify the UF workshop.  The deadline to apply is the end of the day on _________, and we will send out acceptance notifications by ___________. 
> 
> Again, thank you for your support of UF Carpentries!
> 
> Sincerely,

Note that there are a few details to fill in regarding the timeline.

**Comment by elisemorrison** [comment]
I think that email looks great - very thorough and clear. Thank you for drafting it! The one thing that we might want to include is some language below, regarding how people will use the training. Other than that, I think it looks good to go!

"...to specify the UF workshop. When filling out the form, applicants should also describe how they plan to use the tools/skills gained from the workshop in the “anything else?” text box at the bottom of the application. The deadline to apply is..."

Do we want to set the deadline to March 25th, then acceptance notifications out by March 29th or April 1st (if judges want a weekend to look things over), then people will be notified a week before the workshop, so they can plan accordingly? I'm flexible with dates - just throwing some options out there. Thoughts?

**Comment by gklarenberg** [comment]
@elisemorrison and @stuckyb The 29th might be a little short - Maneesha said they need 2-3 days to get the list (applications) to us.
I'd propose:
now - send email to supporting departments
Friday 8th and/or Monday 11th - general email to everyone
Monday 18th - reminder email
Monday 25th 11.55 pm (midnight) - submission deadline
Thursday 28th - get list from Carpentries
28-31 - evaluate (sorry, over the weekend, but I plan to evaluate on Friday)
1 April - MEET to resolve any issues and make final decision, send out acceptance emails

**Comment by gklarenberg** [comment]
And thanks so much @stuckyb Email looks perfect!

**Comment by elisemorrison** [comment]
I think that plan sounds great! Thanks @gklarenberg and @stuckyb!

**Comment by elisemorrison** [comment]
> 
> 
> > Btw - officially our membership says we can train 15 people? See https://carpentries.org/membership/ Is this really a thing? Since I think in all the previous instructor trainings we trained more people
> 
> My guess is that the 15 refers to being trained online (as with the Silver-level membership), but that the capacity for in-person training depends on space and # of instructor trainers that can be present.

I'm getting the UF Conferences registration set up with Alethea and Flora - what's our cap for the instructor training?

**Comment by ha0ye** [comment]
I think 24 is the usual number. Looks like we sent 25 invites last time, with 19 eventual registrants.

**Comment by elisemorrison** [comment]
Thanks!

**Comment by stuckyb** [comment]
Thanks for the quick feedback, everyone!  I agree with everything proposed, except I will suggest one small change to the timing of the announcements: it might make sense to send the sponsor emails and general announcements out at about the same time.  I don't there is an advantage to sending the sponsor emails earlier, and if everything goes out at once, there might be potential for less confusion (or fewer questions for us to handle).

**Comment by stuckyb** [comment]
Here is a revised draft email incorporating Elise's and Geraldine's comments/suggestions (I also made some small revisions to improve brevity):

> Hello,
>
> On behalf of the board of the UF Carpentries Club, I want to thank you for your financial support of our mission to provide affordable and accessible informatics training for the UF community in an inclusive learning environment.
>
> On April 8 and 9, we will be hosting a Carpentries instructor training workshop here at the University of Florida (you might have noticed a recent email announcement about this workshop).  The purpose of this workshop is to train instructors to use effective, evidence-based instructional practices while teaching Data and Software Carpentry workshops.  After the workshop, participants will have the opportunity to complete Carpentries instructor certification and become eligible to teach two-day Carpentries workshops.
>
> Because we only have space for 24 participants, we normally use a short application and a set of merit-based application review criteria (LINK HERE) to select workshop participants.  However, because _____________ is a financial sponsor of UF Carpentries, ____________ has a reserved seat for ___ participant in the workshop.  You do not need to do anything in particular to use this/these reserved seat(s).  We ask that you simply encourage people in your department to apply for the workshop.  We will evaluate their applications using the same criteria mentioned above, but we will guarantee that at least one person from your department gets a seat at the workshop.  In the case that not everyone from your department who applies makes the initial cut, we will contact you to see if you would like to have input on who receives invitations to participate.
> 
> For reference, here is a summary of the application instructions from the workshop announcement email: To apply for the instructor training workshop, please fill out the form at https://amy.software-carpentry.org/forms/request_training/.  Use the code "florida-april2019" in the "Group name" box to specify the UF workshop. When filling out the form, applicants should also describe how they plan to use the tools/skills gained from the workshop in the “anything else?” text box at the bottom of the application. The deadline to apply is the end of the day (midnight) on Monday, March 25, and we will send out acceptance notifications by April 1. 
> 
> Again, thank you for your support of UF Carpentries!
> 
> Sincerely,

**Comment by gklarenberg** [comment]
Has the email gone out to the sponsoring departments? Will we send out the general email today?

**Comment by stuckyb** [comment]
Per my comment above, I'm in favor of sending both emails out at about the same time.  So yes, let's send them today!
