### ISSUE TITLE
Agenda Items for Board Meeting on March 12, 2019

### ISSUE THREAD

**Issue by elisemorrison** [UF-Carpentry/Coordination#89]
Here's the agenda. Feel free to add additional items if I missed anything. Alethea and Taylor have confirmed that they'll attend the meeting.

* Approve previous meeting's minutes 
    https://github.com/UF-Carpentry/website/blob/master/_minutes/Board-2019-02-19.md
* Discuss with Alethea: 
    * Workshop waitlist and priority registration
    * Modifying workshop sign in sheets
* Discuss EPI workshop with Taylor Paisie
    * HPC lesson
    * Instructors
* April Instructor Training
* REC workshop update
* IFAS update, May 6th workshop details
* Travel Awards
* Other Items

Link: https://hackmd.io/shAZDxmJSKWH7wsHcem4dQ#

**Comment by gaurav** [comment]
I asked my friend Kim if she's available to design a logo for us. She says she's pretty busy this month, but might have time in April-May. She usually charges $400 for designing a logo, so we should probably talk about whether we're willing to spend that at one of this month's board meetings.

**Comment by elisemorrison** [comment]
That sounds great! I'll add it to the agenda
