### ISSUE TITLE
Criteria for awarding travel grants

### ISSUE THREAD

**Issue by mjcollin** [UF-Carpentry/Coordination#9]
The workshop fees have been set to accumulate funds in our account at the UFII. This account must be spent out since we are not permitted to generate revenue. We decided to award instructors grants to support travel as that is procedurally easy to do from this account.

Some straw criteria for awards:

- Must have instructed at 2 workshops in last 2 years
- Slight weight to more frequent teachers (something like ln(workshops) ) to avoid this being dominant
- Travel's value to a) UF Carpentries or b) growth/career of instructor?
- Likelihood of instructor finding rest of needed funds for travel (matching?)

**Comment by justinmillar** [comment]
A potential criterion (related to the caveat in second point) could be a negative weight to individuals who have previously received funding from the UF Carpentries Club.

**Comment by justinmillar** [comment]
Also, we will need criteria for which activities are eligible funding. For instance, potential applications may be seeking travel funds for:

- Instructing in a workshop outside of UF
- Participating in The Carpentries-related events (i.e. CarpentryCon)
- Attending additional training or interacting with other Carpentry clubs
- Non-Carpentry related activities, such as presenting material at a related conference

**Comment by mjcollin** [comment]
Today's crazy idea: review applications anonymously. Prompted by: https://www.nature.com/articles/d41586-018-02743-2

**Comment by mjcollin** [comment]
Prioritize figuring out how to support someone at CarpentryCon

**Comment by fmichonneau** [comment]
FYI, it is not on the website (yet) but the early bird rate for CarpentryCon has been extended until March 23rd.

**Comment by mjcollin** [comment]
I started a draft for an amendment to the charter on travel awards:

https://docs.google.com/document/d/1qEP6uz2aNNi6oVHQUxGmyChIJa5dRTHcnvUTM2uJ030/edit?usp=sharing

**Comment by mjcollin** [comment]
RE blind review from Simona:

"Blind review meaning that the committee has to evaluate applications without knowing who the applicant is? I think this has pros and cons. Sometimes knowing who submitted a certain application could be useful because it might provide context that helps deciding about the criteria. Of course we would have to assume impartiality of the evaluation committee. I would feel ok with assuming that, but what do you guys think?"

**Comment by mjcollin** [comment]
Final-ish version is up, closing:

https://github.com/UF-Carpentry/Coordination/wiki/Travel-Awards
