### ISSUE TITLE
Best ways to coordinate use of our official Twitter account

### ISSUE THREAD

**Issue by gaurav** [UF-Carpentry/Coordination#90]
I wanted to collect some suggestions on how best to coordinate use of our Twitter account at https://twitter.com/UFCarpentries.

On a technical level, I believe the account is registered to @KristinaRiemer's e-mail address. We should probably transfer to that our Gmail account, but I don't think that's urgent (although we should change the web address for that account to https://www.uf-carpentries.org). I think the account is set up through [TweetDeck Teams](https://help.twitter.com/en/using-twitter/tweetdeck-teams) so that @ha0ye can post to it as well. Would it be possible to give a bunch of board members access to this account?

In terms of what content we should be posting there, it looks like so far we mostly use it for promoting events and sharing information about relevant organizations. @josephaandreoli suggested to a bunch of us on Facebook recently that we should share an R joke on the official UF Carpentries account, and I think that would be a great idea! I like the idea of letting any board member post to our Twitter account without any particular constraints to start with, and then making up rules and constraints as we need them. What do you all think?

**Comment by ha0ye** [comment]
Since it is an account that represents our organization, I think some general guidelines on posting and RTing would be good - sharing announcements of events and opportunities to our target audience falls within that scope. I've shied away from following folks with the account, and I think we may want some rules there and maybe do some management there.

**Comment by ha0ye** [comment]
Ground rules are good for making sure I only subtweet from my personal account.

**Comment by gaurav** [comment]
I think we've now got the infrastructure in place to coordinate use of our official Twitter account via TweetDeck, so I'm going to close this issue. Please reopen it if I've missed anything! The one thing that's left is writing up a social media policy, which is covered by #105.
