### ISSUE TITLE
Agenda items for Board Meeting on April 16, 2019

### ISSUE THREAD

**Issue by josephaandreoli** [UF-Carpentry/Coordination#93]
Hi all, terribly sorry for the delay. Please add the agenda items you would like to discuss for our next meeting. I was thinking of sending out an announcement about our meeting on Sunday afternoon so that everyone has a chance to add in agenda items. 

1.  Approve last meeting's minutes https://github.com/UF-Carpentry/website/blob/master/_minutes/Board-2019-03-26.md
@stuckyb I couldn't find these on the minutes page of the workshop
2. Instructor Training Recap
3. Last minute preparation for EPI workshop
4. @elisemorrison logo design 
5. @josephaandreoli draft announcement and metrics on travel award applicant pool
6. TREC Workshop 
7. Biodiversity Research Workshop, check out current discussion here https://uf-carpentries.slack.com/archives/CEDRQ4Y0Y/p1554209794006700
8. ResBaz planning and coordination
9. Long-term workshop schedule

**Comment by elisemorrison** [comment]
It would be good to include a brief discussion about a need-based “scholarship” for people who cant afford the workshop fees.

**Comment by gklarenberg** [comment]
Feedback from EPI workshop instead of last minute prep

**Comment by gaurav** [comment]
Minutes will be at https://hackmd.io/oyUzH5iuQU6-2ErWMpkbRw?both if you want to look or edit!
