### ISSUE TITLE
Obtain the stickies and post-training survey results from 2019-04-08-ttt-UF

### ISSUE THREAD

**Issue by gaurav** [UF-Carpentry/Coordination#94]
We should obtain and record the feedback we got from [2019-04-08-ttt-UF](https://fmichonneau.github.io/2019-04-08-ttt-UF/), both in the form of post-workshop stickies as well as the post-training survey.

**Comment by ha0ye** [comment]
I talked to @fmichonneau, and the post-its aren't available anymore, but we'll get the pre- and post- survey results.
