### ISSUE TITLE
Best place to document workshop-specific suggestions

### ISSUE THREAD

**Issue by gaurav** [UF-Carpentry/Coordination#96]
I've incorporated suggestions from the Instructor Training debrief yesterday into our [*Organizing a Workshop* wiki page](https://github.com/UF-Carpentry/Coordination/wiki/Organizing-a-Workshop/_compare/d0c0c21e40070c8ad0935826441960abc9b1ae7b...7f39aedc7ef40ecc7a100c087dd737795dd37139). We [also have suggestions](https://github.com/UF-Carpentry/website/pull/35/files#diff-d9b08e1f533502eb82a1b974de7a3f73R54) from the [UF EPI Genomics workshop](https://uf-carpentry.github.io/2019-04-11-ufepi-genomics/), which is pretty specific to the genomics curriculum.

What would be the best way to keeping track of curriculum-specific suggestions? I think we should have one wiki page with sections for each the curricula, but I thought I'd suggest it here first!

**Comment by ha0ye** [comment]
Agree, some sort of best-practices compendium would be good for organizers and instructors - worth noting that the Carpentries mothership is aware of this knowledge gap in implementing workshops, but current avenues (e.g. the discussion forum and community discussion calls) aren't quite there yet.

Which is to say, we can and should build our own, and keep one thought in the back of our mind about scaling it up for input and re-use by other places, I think.

**Comment by picardis** [comment]
Is this the same as #106 ?

**Comment by gaurav** [comment]
Yes, it is! Let's close one of these?

**Comment by picardis** [comment]
See #106 (now closed)

**Comment by picardis** [comment]
Lol closed both by accident

**Comment by gaurav** [comment]
I took a stab at creating a wiki page for organizing this: https://github.com/UF-Carpentry/Coordination/wiki/Curriculum-specific-notes

How can we make it more useful?
