### ISSUE TITLE
Agenda items for Board Meeting on 2019, April 30

### ISSUE THREAD

**Issue by ha0ye** [UF-Carpentry/Coordination#97]
Here's a preliminary list - please add any agenda items that you'd like to discuss for our next meeting.

1. Approve last week's minutes - https://github.com/UF-Carpentry/website/pull/35
2. Status of travel awards
3. Status of logo design
4. TREC workshop (currently underway)
5. Biodiversity Research Workshop (2019, May 06)
6. ResBas planning
    - coordination with other groups (UF Libraries, UF DSI, UF Innovation Hub, Gainesville R-Ladies, ??)
7. Long-term community building strategy
8. Long-term workshop schedule
    - UF/USDA workshop (August?)
9. Funding for Carpentries membership renewal
    - IFAS support for future REC workshops
10. Need-based scholarship / fee reduction
11. Backup laptops for workshop attendees
12. Social media / website guidance
13. chair and secretary for next meeting (May 14)

**Comment by stuckyb** [comment]
I received an email from Adam Rivers, a computational biologist with the USDA Agricultural Research Service in Gainesville, asking if we'd be interested in partnering with him to run a workshop open to both UF and USDA participants some time in August.  (I believe Adam has remotely joined a board meeting or two in the past.)  I told Adam we'd discuss this at our next meeting, and I've invited him to join us.

**Comment by gaurav** [comment]
For backup laptops: how far can we get on [iPads borrowed from the UF Libraries](https://cms.uflib.ufl.edu/AccessSupport/laptoppolicies)? I'm guessing not far, but I figured I'd bring it up.

**Comment by ha0ye** [comment]
Ethan White is happy to loan out (up to 2) extra laptops from his lab for us to use (provided we handle wiping the hard drives and doing setup).

**Comment by gaurav** [comment]
I'm taking notes at https://hackmd.io/wvpQiFWjSwqf44kEc6heHw if you want to follow along!
